### ISSUE TITLE
AMI Maps need to be updated with v15 AMI's

### ISSUE THREAD

**Issue by jtylershaw** [F5Networks/f5-aws-cloudformation#100]
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/AMI%20Maps

As the title states - the AMI Maps only show 11.5.4.2.0.291 through 14.1.2-0.0.37.  Please update with v15 AMIs.

Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for raising this issue. I've created internal ID ESECLDTPLT-1975 to get these updated.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
