### ISSUE TITLE
AMI cannot be described

### ISSUE THREAD

**Issue by arunprakashv** [F5Networks/f5-aws-cloudformation#101]
## Do you already have an issue opened with F5 support?
No
## Description
Error when executing "Application1Stack" of "https://f5-cft.s3.amazonaws.com/quickstarts/v0.0.0.3/templates/f5/master.template":
AMI cannot be described (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 457bfd16-9988-4324-b90c-7c98ed5991e1)

## Template
https://f5-cft.s3.amazonaws.com/quickstarts/v0.0.0.3/templates/f5/application.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

1 - Unable to install F5 WAF.

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by hparr** [comment]
This is also impacting the learning stacks.

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I've filed a bug for this, internal ID ESECLDTPLT-2019.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
