### ISSUE TITLE
Provide option in CFTs to alter image volume size

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-aws-cloudformation#102]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

(This is a reopening of issue #59, which was closed without response).

The present supported CFTs default to a fixed volume size of (I think) 30Gb. For some applications, this is not sufficient. Provide an option to make VolumeSize a parameter. We've manually altered the template with a static value, but would like to see it in the supported template.

## Template
For bugs, enter the template with which you are experiencing issues below.

f5-existing-stack-across-az-cluster-byol-3nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.
3
Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
Agree, looking at another template the disk size is 100GB.

   "Properties": {
    "BlockDeviceMappings": [
     {
      "DeviceName": "/dev/xvda",
      "Ebs": {
       "DeleteOnTermination": "true",
       "VolumeSize": "100",
       "VolumeType": "gp2"
      }
     },

If you use customImage to deploy a v12.x AMI ID from marketplace and use Best 1Gb, CFT stack will fail because the v12 AMI requires 126GB, but the CFT stack only creates a 100GB size.

To repro:
1. launch template - https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic/existing-stack/payg
2. populate all required fields
3. use AMI ID ami-b312c5ce for the "customImage" field
4. Deploy
5. Stack fails due to 100GB disk size, AMI requires at least 126GB

**Comment by shyawnkarim** [comment]
@C0missar, sorry for no response on issue #59. I've added this RFE to our backlog, internal ID ESECLDTPLT-2020.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
