### ISSUE TITLE
S3 permission issue with latest CFT

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation#105]
## Do you already have an issue opened with F5 support?
no

## Description
New templates were released. Clicking on yellow launch button takes you to AWS console but throws S3 access error. This was a previous ticket. Reference https://github.com/F5Networks/f5-aws-cloudformation/issues/87

Workaround = upload template to your own S3 bucket, and call CFT from your S3 bucket.

## Template
All AWS templates

## Severity Level
3

**Comment by JeffGiroux** [comment]
Tested again just now and the error is gone. What was the fix? According to the last time I opened this ticket, it was suggested additional checks were added to avoid the access error. Seems that AWS changed something that is messing with your access checks again. Refer to https://github.com/F5Networks/f5-aws-cloudformation/issues/87#issuecomment-564285520

**Comment by mikeshimkus** [comment]
The fix was to manually set them to public this morning. We programmatically upload templates to S3 and make them public, but apparently failed at the latter.  Launch links were checked but will always work if the person checking them is logged in to AWS...
