### ISSUE TITLE
HA_API CFT : CloudFormation end with Create Complete while INIT process is still ongoing. DSC configuration fails

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-aws-cloudformation#106]
## Issue

HA_API CFT : CloudFormation end with Create Complete while INIT process is still ongoing. DSC configuration fails.

## Description
After the deployment of HA API CFT, Cloud Formation finishes with CREATE COMPLETE message that lead to think that BIG-IPS are fully configured and ready to use.

Actually after the CREATE COMPLETE, you have to wait up to 10 minutes so that all Cloud init scripts finish the configuration.
If an admin connects to BIG-IP right after the "Create Complete" and change admin password (as normal procedure at first login), it breaks Cloud INIT ongoing process and DSC is not fully configured (aka secondary unit not able to join DSC)

# Proposed solution
In the CFTs, introduce CreationPolicy attribute and WaitCondition handler in order to track status of a configuation process and coordinate Resource Creation with external actions we execute (aka DSC configuration, password change, etc).
With proposed changes, CloudFormation will finishes with CREATE COMPLETE status AFTER all big-ips configaration tasks are finished

## Template
all HA_API CFTs variants

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 

Severity level definitions:

 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.

**Comment by shyawnkarim** [comment]
This is a known issue that we are already tracking internally with ID ESECLDTPLT-1938.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 5.7.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.7.0).
