### ISSUE TITLE
AWS Auto Scaling (autoscale, auto-scale) does not remove devices from Device Group after scale Event

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-aws-cloudformation#107]
## Do you already have an issue opened with F5 support?
Nope

## Description
Autoscale works but after the scale in the event, the device group is not updated to remove the deleted devices.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/ltm/via-lb/1nic/existing-stack/payg

## Severity Level
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.

If the scale events manages to create more then 8 dead nodes, the next scale will fail since clusters only support 8 nodes.

![Pasted_Image_6_26_20__9_21_AM](https://user-images.githubusercontent.com/20847865/85879019-7d152c00-b78e-11ea-842d-4f2c1c944958.png)

Its looks like there was an Azure issue with the same problem: https://github.com/F5Networks/f5-aws-cloudformation/issues/104

**Comment by elliotwilcock-cli** [comment]
Thank you for reporting the issues. I have created an internal issue ESECLDTPLT-2180 to track this.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
