### ISSUE TITLE
Multiple VIPs for failover templates

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#110]
## Do you already have an issue opened with F5 support?
No

## Description
The failover templates do not provide an option for configuring multiple F5 VIPs, i.e. multiple secondary IP addresses and multiple associated Public IPs (if applicable). 

Note that the latest version of the CFE script (v1.3.0 https://github.com/F5Networks/f5-cloud-failover-extension) supports failover for multiple Public IP objects.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/2nic/existing-stack/payg
and all other via-api failover templates 

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thanks for raising this enhancement request. We are now tracking this enhancement with internal ID ESECLDTPLT-2241.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
