### ISSUE TITLE
Routes to fail over are not exposed as template parameters

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#112]
## Do you already have an issue opened with F5 support?
No

## Description
The failover templates have hard-coded CFE declaration with the only "scopingAddressRanges" range set to 192.0.2.0/24 as an example. This range/subnet value should be exposed as a template parameter instead.

Ideally, the templates should support adding multiple ranges/subnets listed (e.g. coma-delimited) in as this parameter's value. The template should then convert the list into the correct multi-range declaration, as described by Nicolas Ménant in https://github.com/F5Networks/f5-cloud-failover-extension/issues/35

Note that CFE route-failover feature is critical in across-net (across-AZ) cases as it is the only available HA mechanism when "Provision Public IP addresses for the BIG-IP interfaces" parameter is set to "No" (or when applications are accessed via both Private as well as Public IP addresses). See https://devcentral.f5.com/s/articles/deploy-bigip-in-aws-with-ha-across-azs-without-using-eips-33378 for details.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/2nic/existing-stack/payg
and all other via-api failover templates

## Severity Level
3

**Comment by shyawnkarim** [comment]
Thanks for raising this enhancement request. We are now tracking this issue internally with ID ESECLDTPLT-2242.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

If this feature is still important to you, please submit an issue in the V2 repo.
