### ISSUE TITLE
Why traffic-group = none

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#113]
## Do you already have an issue opened with F5 support?
No

## Description
Documentation for failover templates states that: "In order to pass traffic from your clients to the servers through the BIG-IP system, you must create at least two virtual servers on the BIG-IP VE using Traffic Group None..."

It is not clear why the traffic-group=none setting is required. The template does not change the default traffic-group configuration (i.e. only traffic-group-1 is present) and the cluster operates as active-standby for traffic-group-1 at F5 level. As far as I can tell, the CFE script initiates failover at the AWS level when it detects that the a device is changing its state from standby to master.

It also should be clarified whether setting traffic-group to none may impact the operations of persistence mirroring (e.g. mirroring to support source-IP-based persistence) as mirroring is performed on a traffic-group basis (https://support.f5.com/csp/article/K13478).

It is possible that this recommendation is due to undocumented limitations of CFE. For example, it could be a workaround to reduce the impact of the incorrect AWS-level failover behavior described in https://github.com/F5Networks/f5-cloud-failover-extension/issues/36 . If this is the case, the workaround nature of the recommendation should be documented and more details should be provided (e.g. regarding persistence mirroring as per above). 

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/2nic/existing-stack/payg
and all other via-api failover templates

## Severity Level
4

**Comment by shyawnkarim** [comment]
Closing.

Documentation for this issue was added in [Release 5.7.1](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.7.1) and it can be found in the [Cloud Failover Extension FAQ](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/faq.html).
