### ISSUE TITLE
Internet access prerequisites and VIP-only allocation of Public IP addresses

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#114]
## Do you already have an issue opened with F5 support?
No

## Description
One of the failover templates' prerequisites contains the following statement: "... the subnet for the external network requires a route and access to the Internet for onboarding BIG-IP)." This statement implies that access from BIG-IPs to the Internet can be removed/disabled after the template is implemented. In particular, it implies that Public IP addresses can be unassigned from the SelfIP private addresses after deployment (to reduce the total subscription costs and to improve security posture).

In reality, access from BIG-IP to AWS EC2 and S3 is commonly provided via the Internet. 

Technically, AWS endpoints can be configured to replace the via-the-Internet access (see https://devcentral.f5.com/s/articles/Using-VPC-Endpoints-with-Cloud-Failover-Extension), but this design option modifies the environment within the VPC in question and may not be suitable outside of the green-field implementations.

It appears (assuming AWS endpoints are not used), the post-deployment "Internet access via external" requirement makes it impossible to remove the Public IPs (PIPs) corresponding to the selfIP private addresses. This constraint is due to AWS design routing limitations - default route within the route table assigned to the subnet in question can be pointed to either an IGW or a NAT Gateway. In the former case BIG-IP without selfIP-PIPs would not have via-the-internet access to AWS EC2 and S3, in the latter the connectivity between the Internet clients and VIP-PIPs would be broken.

Please provide clarifications in the documentation. Ideally, the templates should be modified to provide a parameter for disabling assignment of Public IPs to management IPs and SelfIPs (whilst still assigning Public IPs to VIPs).

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/2nic/existing-stack/payg
and all other via-api failover templates

## Severity Level
4

**Comment by shyawnkarim** [comment]
Thank you for reaching out with this issue.  I've created two tickets for this that we are now tracking internally:

1. Internal ID AUTOSDK-485 for documentation on how to use endpoints post deployment once internet access is no longer required.
2. Internal ID ESECLDTPLT-2294 to add an additional parameter to the failover via-api templates for disabling assignment of Public IPs to management IPs and SelfIPs (whilst still assigning Public IPs to VIPs).

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
