### ISSUE TITLE
Instance type not supported

### ISSUE THREAD

**Issue by harrykleinb** [F5Networks/f5-aws-cloudformation#117]
## Description
This case is relative to issue #115 CFT fails - Error: instance configuration for this AWS Marketplace product is not supported.

After some tests, it seems that the issue is with the instance type:
 	
The CFT deployment fails with the error message "instance configuration for this AWS Marketplace product is not supported" when the instance type selected is m5.4xlarge. 

Foir instance, it works perfectly with an instance type m4.2xlarge.

The tests have been done in us-east-1 (North Virginia).

 
## Template
BIGIP-Across-Az-Cluster-3nic-PAYG in North Virginia Region (us-east-1): https://f5-cft.s3.amazonaws.com/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template

## Severity Level

Severity: 3

**Comment by vvt137** [comment]
The instance type m5.4xlarge did not work when I used the corresponding template options in https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic/existing-stack/payg. The region that I tried to use this instance type in was ap-southeast-2 (Sydney). The error messages was similar to this one:

*The instance configuration for this AWS Marketplace product is not supported. Please see the AWS Marketplace site for more information about supported instance types, regions, and operating systems. (Service: AmazonEC2; Status Code: 400; Error Code: UnsupportedOperation; Request ID: bdd86f45-7f6f-4534-9448-b0d325253a63)*

The image type m5.2xlarge did not work either. This one is not listed in the template, so I customised the template for this test. In theory, the customisation should have been successful as m5.2xlarge (as well as m5.4xlarge) is listed in  https://clouddocs.f5.com/cloud/public/v1/matrix.html.

The instance types m5.large and m5.xlarge worked all right from the same template and in the same region.

**Comment by vvt137** [comment]
I found that m5.4xlarge instance type can be deployed in the case of the BYOL image. However, only 4 TMMs/CPUs are shown in the output of `show sys tmm-info` command (if m5.12xlarge instance type is used all 8 TMMs/CPUs are shown).

**Comment by shyawnkarim** [comment]
@harrykleinb I just deployed your template into us-east-1 with instance type m5.4xlarge and the stack was created successfully. Are you still experiencing this error?

**Comment by shyawnkarim** [comment]
Closing.

I deployed this template with instance type m5.4xlarge in both North Virginia and Sydney today and saw no errors. Please reopen if you continue to experience issues.
