### ISSUE TITLE
Cluster lifecycle enhancement (deprovisioning)

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-aws-cloudformation#123]
## Do you already have an issue opened with F5 support?
yes, 1-6591259950

## Description
Enhancement: for full IaC deployment mode, I would like to request the following for the cluster deprovisioning/destroy:
Integrate a Lifecycle Hook for instance termination with the SQS and run the following condition on the cluster:

If the instance is the last instance in the cluster (and is primary, but should), do
- empty the S3 bucket
- unlicense itself to the BIG-IQ
- remove its own scale-in protection
- complete-lifecycle-action to go in Terminating:Proceed state

Else, do nothing, and complete-lifecycle-action to go in Terminating:Proceed state

With this, a destroy of the cluster would not require any manual step (the deletion of the bucket is performed by the stack, but the bucket needs to be empty).

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by shyawnkarim** [comment]
This enhancement request is being tracked internally with ID ESECLDTPLT-2202.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
