### ISSUE TITLE
ENI tags required for CFE failover routes are not set

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#124]
## Do you already have an issue opened with F5 support?
No

## Description
The following tags required by CEF are not set to the NICs/ENIs by the failover templates:

- `f5_cloud_failover_label:<Stack Name>` not set for the **internal** (eth2) interface (3-NICs failover templates only)
- `f5_cloud_failover_nic_map:<NIC ref>` not set for any data-plane interfaces (2-NICs and 3-NICs failover templates)

The first of these issues causes problems for the operations of CFE in "Multiple Next Hop Addresses" scenario (which is why I am assigning severity 2 to this ticket). Refer to issue https://github.com/F5Networks/f5-cloud-failover-extension/issues/44 for more details.

The impact of the second issue is not clear as the CFE documentation does not document the intended use of the `f5_cloud_failover_nic_map` tags, see https://github.com/F5Networks/f5-azure-arm-templates/issues/172 (which remain outstanding). Reportedly, the current version of Azure via-api templates do tag interfaces with `f5_cloud_failover_nic_map`.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/payg
and all other via-api failover templates

## Severity Level
2

**Comment by elliotwilcock-cli** [comment]
I have created the internal issue ESECLDTPLT-2181 to track this.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
