### ISSUE TITLE
VIP EIP association should refer to Bigip2 instead of Bigip1

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#126]
## Do you already have an issue opened with F5 support?
No

## Description
VIP EIP association `Bigip1VipEipAssociation` code in Failover templates should refer to `Bigip2subnet1Az2Interface` (rather than `Bigip1subnet1Az1Interface`) for both `NetworkInterfaceId` and `SecondaryPrivateIpAddresses` settings.

When the template is initially deployed the BIG-IP2 instance is consistently becoming an Active system within the HA cluster. However, in its current form the VIP EIP association leads to the EIP not becoming operational until HA failover is initiated at least once.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/failover/across-net/via-api/3nic/existing-stack/payg/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template
and all other Failover templates

## Severity Level
3

**Comment by elliotwilcock-cli** [comment]
I have created the internal issue ESECLDTPLT-2182 to track this.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
