### ISSUE TITLE
Unused environment variables set by custom-config.sh of failover templates

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#127]
## Do you already have an issue opened with F5 support?
No

## Description
A number of environment variables set in /config/cloud/aws/custom-config.sh that are not used anywhere else in the scripts created by the failover template. 

In particular, EXTPRIVIP and PEER_EXTPRIVIP variables are set using the values of the Secondary IP addresses on "external" NIC/ENIs and appear not be used anywhere else. It may be desirable to remove the Secondary IP addresses after the stack is deployed in the "purely private" implementations (as only "floating" IP ranges would be used as described in https://devcentral.f5.com/s/articles/deploy-bigip-in-aws-with-ha-across-azs-without-using-eips-33378 ). However, removing these objects appears risky whilst it is unclear whether these variables are actually used.

I think the variables that (apparently) are not used by the deployment would need to be either removed or documented (in the README.md and/or in AWS section of clouddocs.f5.com). E.g., perhaps, these variables are to be used from within the AS3 declarations that can be loaded and executed by the template...

BTW, some of these variables are not created symmetrically within the BIG-IP1 vs BIG-IP2 custom-config.sh files (EER_EXTPRIVIP and VIPEIP are only set by the BIG-IP1's custom-config.sh file) and the rationale for this lack of symmetry is also not documented.

Note that the standalone templates only have one environment variable (PROGNAME), which is used within the custom-config.sh script itself.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/failover/across-net/via-api/3nic/existing-stack/payg/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template
and other Failover templates

## Severity Level
5

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this addition to our documentation request with internal ID ESECLDTPLT-2295.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
