### ISSUE TITLE
Support for disabling hyperthreading

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-aws-cloudformation#128]
## Do you already have an issue opened with F5 support?
No

## Description
AWS instance types recommended for F5 VE implementations by default are provisioned with 2:1 hyper-threading (aka multithreading in AWS documentation). This leads to inefficient use of CPU limits of the F5 VE licenses as only 50% of the full capacity can be used by CPU-intensive calculations such as processing SSL traffic (e.g. m5.xlarge AWS instance with 2 CPU cores will be presented as 4 vCPUs, whilst 200Mbps VE license only allows to use 2 out of 4 of these vCPUs, i.e. only one CPU core).

E.g. the following fragments of code can be added to the "Mappings" and "Bigip1Instance"/"Bigip2Instance" parts of the templates respectively (the additional input-parameter part of the code is not shown) to enable this feature:

    "InstanceTypeMaxCoreMap" : {
     "m5.xlarge": { "MaxCores" : "2"},
     "m5.4xlarge": { "MaxCores" : "4"},
     "m5.large": { "MaxCores" : "1"},
     "m5.12xlarge": { "MaxCores" : "24"},
     "m4.xlarge": { "MaxCores" : "2"},
     "m4.large": { "MaxCores" : "1"},
     "m4.4xlarge": { "MaxCores" : "8"},
     "m4.2xlarge": { "MaxCores" : "4"},
     "m4.16xlarge": { "MaxCores" : "32"},
     "m4.10xlarge": { "MaxCores" : "20"},
     "m3.xlarge": { "MaxCores" : "2"},
     "m3.medium": { "MaxCores" : "1"},
     "m3.large": { "MaxCores" : "1"},
     "m3.2xlarge": { "MaxCores" : "4"},
     "cc2.8xlarge": { "MaxCores" : "16"},
     "c5.xlarge": { "MaxCores" : "2"},
     "c5.large": { "MaxCores" : "1"},
     "c5.4xlarge": { "MaxCores" : "8"},
     "c5.9xlarge": { "MaxCores" : "18"},
     "c4.xlarge": { "MaxCores" : "2"},
     "c4.8xlarge": { "MaxCores" : "18"},
     "c4.4xlarge": { "MaxCores" : "8"},
     "c4.2xlarge": { "MaxCores" : "4"},
     "c3.xlarge": { "MaxCores" : "2"},
     "c3.8xlarge": { "MaxCores" : "16"},
     "c3.4xlarge": { "MaxCores" : "8"},
     "c3.2xlarge": { "MaxCores" : "4"},
     "c5n.2xlarge": { "MaxCores" : "4"},
     "c5n.4xlarge": { "MaxCores" : "8"}
    }

    "CpuOptions": {
     "Fn::If": [
      "noMultiThreading",
      {
       "CoreCount" : { "Fn::FindInMap": [ "InstanceTypeMaxCoreMap", { "Ref": "instanceType" }, "MaxCores"] },
       "ThreadsPerCore": "1"
      },
      {
        "Ref" : "AWS::NoValue"
      }
     ]
    }

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic/existing-stack/payg
and all other templates

## Severity Level
5

**Comment by elliotwilcock-cli** [comment]
Thank you for the note. We are tracking this internally with ESECLDTPLT-2183.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
