### ISSUE TITLE
v13 ami map is identical to v15 (and the ami ids are for v15)

### ISSUE THREAD

**Issue by cixelsyd** [F5Networks/f5-aws-cloudformation#129]
## Do you already have an issue opened with F5 support?

Yes, but they said they could not help: C3358308

## Description
Describe the problem you're having or the enhancement you'd like to request.

I have a complicated upgrade process that i need to perform. I'm migrating from a hardware on-prem bigip LTM device to an AWS VE device. Additionally, my on-prem device is running OS 11.5.3, so i have mutiple upgrade steps to perform.

I need the AMI for us-east-1 for a BYOL 'ALL/BEST' virtual appliance, however, it appears the older AMIs embedded inside the older CF templates have been de-registered. I did find the "AMI-mapping" folder inside the github repo, but the issue is that the v13 and v15 mapping files are identical (and point at v15):

○ → md5 docs/v13-ami-map.json
MD5 (docs/v13-ami-map.json) = ec95755a7f62ab098ba72b1b6eb37990

○ → md5 docs/v15-ami-map.json
MD5 (docs/v15-ami-map.json) = ec95755a7f62ab098ba72b1b6eb37990

I need someone to fix this file inside github (or at least provide me with the valid AMI ID reference):
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/AMI%20Maps/13.1.3.4-005/cached-byol-region-map.json

## Template
For bugs, enter the template with which you are experiencing issues below.

https://github.com/F5Networks/f5-aws-cloudformation/blob/master/AMI%20Maps/13.1.3.4-005/cached-byol-region-map.json

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by elliotwilcock-cli** [comment]
Thank you for reporting this issue. We are tracking this internally as ESECLDTPLT-2184.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 5.7.1](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.7.1).
