### ISSUE TITLE
S3 access denied when trying to launch some stacks

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-aws-cloudformation#131]
From this page:
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/template-index.md

I’m getting S3 Access Denied errors trying to run at least the following

https://f5-cft.s3.amazonaws.com/f5-prod-stack-payg-1nic-bigip.template
https://f5-cft.s3.amazonaws.com/f5-prod-stack-byol-1nic-bigip.template
https://f5-cft.s3.amazonaws.com/f5-prod-stack-bigiq-1nic-bigip.template

**Comment by thomsonjames** [comment]
If these are deprecated, I guess they should be removed from the readme?

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. It looks like every production stack launch link is broken. We are now tracking this documentation bug internally with ID ESECLDTPLT-2293.

**Comment by shyawnkarim** [comment]
Closing.

The fix to this issue was included with [Release 5.12.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.12.0).
