### ISSUE TITLE
Template failing to build F5's in US-GOV-EAST region

### ISSUE THREAD

**Issue by misterx280** [F5Networks/f5-aws-cloudformation#138]
## Description
Describe the problem you're having or the enhancement you'd like to request.

Deploying the 3 nic clustered cross AZ F5 template fails to build a configured F5 HA pair. The CFT runs with 0 errors abut when I log onto the F5s they are in a standalone state with no networking, resource provisioning, or HA configurations. The F5s are licensed and ready for initial setup.  

## Template
For bugs, enter the template with which you are experiencing issues below.

f5-existing-stack-across-az-cluster-payg-3nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1. without this template I cannot continue the F5 build in my VPC. 

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
Anything obvious stick out in the log files? Check /var/log/cloud directory for log errors.

**Comment by misterx280** [comment]
Deploying new stack and checking right now.


Chris

**Comment by misterx280** [comment]
There is no /var/log/cloud directory but there are two logs called cloud-init.log and the other is cloud-init-output.log.

**Comment by misterx280** [comment]
roger, will check the IGW and NAT gateways.

**Comment by hparr** [comment]
Note that the SG/NACL needs to also allow ICMP as that is one of the network connectivity checks used by the onboarding process.

**Comment by hparr** [comment]
That is good news - happy to help.

**Comment by shyawnkarim** [comment]
Closing. Please reopen if additional help is needed.
