### ISSUE TITLE
AMI ID's seem to be wrong

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-aws-cloudformation#142]
## Do you already have an issue opened with F5 support?
No case opened with support as this is experimental

## Description
Using the quickstart
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/experimental/quickstart/v0.0.0.3/templates/f5

The ami's listed for the Ubuntu image and BIG-IP's are wrong and need updating.
There are A LOT of AMI's listed.  When this was created, was there a script that you had to pull all of the required AMI's and update the templates?

## Template
Ubuntu
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/experimental/quickstart/v0.0.0.3/templates/f5/application.template
and the BIG-IP's
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/experimental/quickstart/v0.0.0.3/templates/f5/f5-bigip.template

## Severity Level
1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
The experimental quickstart folder was updated 9 months ago. For example, the AMI for Best 1000 = ami-04b3b6fb93d8adfa9. When searching the AWS console, this is BIG-IP version ????...not sure as image is no longer found in AWS AMI list :(

Experimental folder could use a good review and update across all subfolders. @mikeshimkus

**Comment by mikeshimkus** [comment]
I created internal issue #2428 for this, thanks for reporting.

**Comment by thomsonjames** [comment]
So far, I've had to replace the AMI's for App servers, BIG-IP's. It's on to the Bastion now. It looks like the script to onboard the bastion isn't working as 16.04 Ubuntu AMI isn't there and updating to use the 18.04 doens't fix it. I'll update once I have more information on what works if I can figure it out

**Comment by thomsonjames** [comment]
I just realized that we just need to update the quickstart AWS bastion templates and scripts to the new versions: https://github.com/aws-quickstart/quickstart-linux-bastion

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
