### ISSUE TITLE
Failed to delete BIGIP-Across-Az-Cluster-3nic-PAYG stack because S3 bucket is not empty

### ISSUE THREAD

**Issue by abbetzler** [F5Networks/f5-aws-cloudformation#144]
## Do you already have an issue opened with F5 support?
No.

## Description

If I delete a CFT stack for the BIGIP-Across-Az-Cluster-3nic-PAYG template, it fails to do so because the S3 bucket created by the template is not empty.

Status reason
The following resource(s) failed to delete: [S3Bucket].

## Template

f5-existing-stack-across-az-cluster-payg-3nic-bigip

## Severity Level

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue. Follow these steps to delete your stack:

1. Navigate to S3.
2. Find the bucket your stack is using and click into it to view its contents.
3. Delete all the contents.
4. Delete the stack.

If this doesn't solve your issue, please let me know.

**Comment by abbetzler** [comment]
Thanks, but I know that deleting the contents of the bucket allows the stack to be deleted. My point is, was it not supposed to be automated? Deleting the stack should also delete the contents of the bucket before attempting to delete the bucket.

**Comment by vkurenyshev-godaddy** [comment]
I do not know how you can automatically empty S3 bucket when you delete CloudFormation stack.
A Lambda function which is triggered when Stack is being deleted and empties S3 bucket? and S3 bucket should be depended on it, that a stack does not try to delete S3 bucket first.

**Comment by shyawnkarim** [comment]
Closing.

At this time we do not plan to automate the deletion of an S3 bucket.
