### ISSUE TITLE
BIG-IP cluster across AZ does not get established, BIG-IPs stay single units

### ISSUE THREAD

**Issue by gwolfis** [F5Networks/f5-aws-cloudformation#145]
Deployed BIG-IPs will not establish a cluster, but stay single units due to missing config.

For the 3NIC deployment the DSC communication is defined at the internal interfaces of the BIG-IP. The Internal port lockdown mode is set to custom and only contains TCP 4353 and UDP 1026. To create the trust you also need TCP 443 and this one is missing and also the internal AWS security Group misses TCP 443.

As a result the trust is not set and BIG-IP setup does not finish correctly.

This situation might not just occur for the PAYG template only. So, please test those as well.

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
I went ahead and deployed this template and the cluster succeeded over 443 on the management port. Is there anything in the logs that says anything about why the cluster failed?

**Comment by f5-applebaum** [comment]
Technically Clustering/Trust Establishment happens on 443 over the MGMT interface. A special rule that allows both instances to talk to each over 443 on MGMT should be created.

https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/failover/across-net/via-api/3nic/existing-stack/payg/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template#L3485

Once trust is established, the instances begin communicating over 4353 to sync their configs and 1026 for the heartbeat.  

Is the trust created (443 over MGMT)?
Is config sync'd (4353 on TMM interface)?
Or is it an Active/Active situation where heartbeat (1026 on TMM interface) is blocked?

**Comment by ab-gmbh** [comment]
Having the same issue with both 2-NIC and 3-NIC PAYG cross-net templates.

Both BIG-IP's stay on as Standalone. No HA configuration on either BIG-IP's.

**Comment by shyawnkarim** [comment]
Closing. Please reopen if this issue persists.
