### ISSUE TITLE
Experimental Template doesnt have c5.2xlarge

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-aws-cloudformation#147]
## Do you already have an issue opened with F5 support?
Yes: C3482374

## Description
Experimental Autoscale does not have c5.2xlarge as an included instance type:

```
  "instanceType": {
   "AllowedValues": [
    "m5.xlarge",
    "m5.4xlarge",
    "m5.large",
    "m5.12xlarge",
    "m4.xlarge",
    "m4.large",
    "m4.4xlarge",
    "m4.2xlarge",
    "m4.16xlarge",
    "m4.10xlarge",
    "m3.xlarge",
    "m3.medium",
    "m3.large",
    "m3.2xlarge",
    "cc2.8xlarge",
    "c5.xlarge",
    "c5.large",
    "c5.4xlarge",
    "c5.9xlarge",
    "c4.xlarge",
    "c4.8xlarge",
    "c4.4xlarge",
    "c4.2xlarge",
    "c3.xlarge",
    "c3.8xlarge",
    "c3.4xlarge",
    "c3.2xlarge",
    "c5n.2xlarge",
    "c5n.4xlarge"
   ]
```

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/experimental/autoscale/ltm/via-nlb/1nic/existing-stack/payg

## Severity Level
2. This is affecting a Private Offer

**Comment by shyawnkarim** [comment]
Is the customer able to add this instance to their template?

**Comment by jmcalalang** [comment]
Yes, I did that workaround. However, it doesn't seem like we should have to. It just looked like the instance was accidentally missed, since other c5 family members were available.

Plus, if we Modify the template; it loses the Supported status.

Cheers,

Jon Calalang
425.971.8991
________________________________

**Comment by shyawnkarim** [comment]
The template you linked to is experimental, which means it already is not supported.

**Comment by jmcalalang** [comment]
Ah truth, my mistake. Still seemed like it was accidently skipped. This was 24 days ago 😊

 

From: Shyawn Karim ***@***.***>
Reply-To: F5Networks/f5-aws-cloudformation ***@***.***>
Date: Friday, March 19, 2021 at 7:58 AM
To: F5Networks/f5-aws-cloudformation ***@***.***>
Cc: Jon Calalang ***@***.***>, Author ***@***.***>
Subject: Re: [F5Networks/f5-aws-cloudformation] Experimental Template doesnt have c5.2xlarge (#147)

 

The template you linked to is experimental, which means it already is not supported.

**Comment by shyawnkarim** [comment]
Closing.

Please reopen if this continues to be a problem.
