### ISSUE TITLE
Include and update AMI maps for latest BIG-IP AWS supported versions

### ISSUE THREAD

**Issue by laul7klau** [F5Networks/f5-aws-cloudformation#148]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.
https://clouddocs.f5.com/cloud/public/v1/matrix.html#cloud-platforms
lists the latest AWS BIG-IP VE supported... 
The AMI maps here: https://github.com/F5Networks/f5-aws-cloudformation/tree/master/AMI%20Maps
do not include the latest versions like 16.x, 14.1.4, 13.1.3.6 that are required when upgrading BIG-IPs in a autoscaling group.

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
This is a known issue, internal ID ESECLDTPLT-1975, and in our backlog. Thanks for reporting.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
