### ISSUE TITLE
Number of production stack templates result in 404 or AWS S3 errors

### ISSUE THREAD

**Issue by minnocentini** [F5Networks/f5-aws-cloudformation#149]
## Description
A number of production stack templates documentation links result in a 404. Additionally a number of launch stack buttons result in an AWS S3 error. 
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Templates located here on the index page:

https://github.com/F5Networks/f5-aws-cloudformation/blob/master/template-index.md

## Template
Few examples are:
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/1nic/production-stack/byol
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/2nic/production-stack/byol
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic/production-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
2 - unable to deploy new instances

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reporting.

This is a known issue, internal ID ESECLDTPLT-2293, and will be fixed in our next release.

**Comment by shyawnkarim** [comment]
Closing.

The fix to this issue was included with [Release 5.12.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.12.0).
