### ISSUE TITLE
Is this project dead and PRs and Issues are useless?

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [F5Networks/f5-aws-cloudformation#155]
Hi Team,

As you have another repo now https://github.com/F5Networks/f5-aws-cloudformation-v2, does it mean this current repository is dead and it does not make sense to create new issues here?

When I create an issue I do not see a GH issue template anymore.

Please provide feedback.

**Comment by shyawnkarim** [comment]
Those V2 templates are our next generation templates, which are designed to be modular and allow for greater control and customization. These V1 templates are not dead and are still supported by F5. Please continue to submit V1 issues here as needed.

**Comment by shyawnkarim** [comment]
Closing. Please reopen another issue if you have more questions.
