### ISSUE TITLE
Create cluster over aws/n. virginia failed for f5-full-stack-payg-1nic-bigip.template

### ISSUE THREAD

**Issue by yaronTTkarni** [F5Networks/f5-aws-cloudformation#159]
https://github.com/F5Networks/f5-aws-cloudformation/blob/main/experimental/standalone/1nic/learning-stack/payg/f5-full-stack-payg-1nic-bigip.template

This is the error:
**API: ec2:RunInstances Not authorized for images: [ami-93fa8284]**

We would like to install bigip in aws/n. virgina and failed.

We need a solution asap

**Comment by JeffGiroux** [comment]
I tried to install the infrastructure folder and I also received the same error when it came to the EC2 instance. 

https://github.com/F5Networks/f5-aws-cloudformation/tree/main/experimental/reference/3nic/infrastructure-only

**Comment by mikeshimkus** [comment]
@yaronTTkarni The current Bitnami LAMP AMI IDs are documented here: https://bitnami.com/stack/lamp/cloud/aws/amis

To deploy in us-east-1, you would need to modify this line of the template with the correct AMI ID for US East (N. Virginia): https://github.com/F5Networks/f5-aws-cloudformation/blob/51c3af188fb11b1b2898d63da90399a3082dcd37/experimental/standalone/1nic/learning-stack/payg/f5-full-stack-payg-1nic-bigip.template#L541 

FYI, the experimental templates aren't supported and will be deprecated soon. Version 2 of our CloudFormation templates has been released here: https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples.  The quickstart 1 NIC template will deploy the full stack, including application.

**Comment by yaronTTkarni** [comment]
thanks, its works

Changed to
"us-east-1": {
    "AMI": "ami-0226c182c5648e5b0"
   },
