### ISSUE TITLE
Issues using the template.

### ISSUE THREAD

**Issue by ahusking** [F5Networks/f5-aws-cloudformation#16]
## Description
When attempting to use the templates, i get the following error:

Template validation error: TemplateURL must reference a valid S3 object to which you have access.

## Template
https://s3.amazonaws.com/f5-cft/f5-existing-stack-byol-2nic-bigip.template

## Severity Level
Severity: 2

**Comment by kskoh** [comment]
Try again.  S3 permissions were not set correctly.

**Comment by ahusking** [comment]
That's worked perfectly.

Thank you
