### ISSUE TITLE
When do you expect to release CF templates with support of latest Cloud Failover?

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [F5Networks/f5-aws-cloudformation#161]
F5 released Cloud Failover recently https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.10.0

When do you expect F5 CloudFormation templates will be updated to include this new version?

**Comment by shyawnkarim** [comment]
We currently don't have an official date but we do plan to release an update sometime in February.

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if you have more questions.
