### ISSUE TITLE
When are you going to release CF with latest CFE support?

### ISSUE THREAD

**Issue by vkurenyshev-godaddy** [F5Networks/f5-aws-cloudformation#162]
Hello Team,

When are you going to release new CF versions with 
1. Latest CFE support https://github.com/F5Networks/f5-cloud-failover-extension/releases
2. Latest AMIs in 15.x and 16.x branches?

I remember I have been told about mid-February and it is almost March.

Please advise! 
Thanks

**Comment by shyawnkarim** [comment]
We are currently working on squeezing in one more item for this release. I'll provide an update on timing as soon as I know more, possibly tomorrow.

**Comment by vkurenyshev-godaddy** [comment]
Thank you @shyawnkarim.

Would it be possible to have a scheduler of new releases?
It will help a lot during projects planning.

**Comment by G-gonzalezjimenez** [comment]
Hi, we would like to have a quick conversation with you to understand the business case scenario? could you reach out to me at g.gonzalezjimenez@f5.com?

Thank you!

**Comment by vkurenyshev-godaddy** [comment]
Hi @G-gonzalezjimenez 
I've sent an email to your address on 7 March, have not got any reply yet :)

Hi @shyawnkarim 
Would it be possible to get an update on the release schedule?

**Comment by G-gonzalezjimenez** [comment]
Hi

Can you send me your email? I never received anything from you.

Thank you



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by G-gonzalezjimenez** [comment]
Hi @vkurenyshev-godaddy could you either share your email here or resend the email to g.gonzalezjimenez@f5.com 
I have not received any email from you.

Thank you

**Comment by shyawnkarim** [comment]
@vkurenyshev-godaddy, can you reach out to @G-gonzalezjimenez? He is the team's Product Manager and in charge of our release schedule.

**Comment by vkurenyshev-godaddy** [comment]
I just sent another email to g.gonzalezjimenez[at]f5.com

**Comment by shyawnkarim** [comment]
Closing. 

Our templates were updated to use the latest CFE with [Release 5.15.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.15.0).
