### ISSUE TITLE
IAM role required updates to include EC2:DescribeSubnets for failover to work

### ISSUE THREAD

**Issue by bohanson** [F5Networks/f5-aws-cloudformation#166]
## Summary
IAM role required updates to include EC2:DescribeSubnets for failover to work
 
## Detail
We used [this template](https://github.com/F5Networks/f5-aws-cloudformation/tree/main/supported/failover/same-net/via-api/3nic/existing-stack/byol) to deploy a pair of devices, however, we want to update routes upon failover between F5 devices.
 
[This section of the template](https://github.com/F5Networks/f5-aws-cloudformation/blob/main/supported/failover/same-net/via-api/3nic/existing-stack/byol/f5-existing-stack-same-az-cluster-byol-3nic-bigip.template#L3141-L3153) appears to be missing a required permission. It's possible that something changed in the underlying cloud, of course.
 
Upon failover our route table was not updated, despite having the correct tags. We saw an error message in /var/log/restnoded/restnoded.log that indicated an error because permission of EC2:DescribeSubnets was missing.
 
We manually updated the IAM role that was created by the template to include this permission, and then failover and update of route table was successful.
 
Can we have this permission added to the IAM role that is created? I see that it is already included in our [documentation](https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#create-and-assign-an-iam-role)
 
## Workaround
After deploying CFT, update the IAM role manually.

**Comment by mikeshimkus** [comment]
@bohanson Thanks for the report, EC2:DescribeSubnets will be included in the next release of the templates (ETA is next week).

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 5.15.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.15.0).
