### ISSUE TITLE
f5-aws-cloudformation-5.11.0 is not deploying

### ISSUE THREAD

**Issue by prudhviraju58** [F5Networks/f5-aws-cloudformation#167]
Do you already have an issue opened with F5 support?
No

Description
Error when executing https://github.com/F5Networks/f5-aws-cloudformation/tree/main/supported/autoscale/ltm/via-lb/1nic/existing-stack/payg

Template

Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

5 - Unable to launch F5 autoscale instance 

Severity level definitions:

Severity 1 (Critical) : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
Severity 2 (High) : Defect is causing major obstruction of system operations.
Severity 3 (Medium) : Defect is causing intermittent errors in system operations.
Severity 4 (Low) : Defect is causing infrequent interuptions in system operations.
Severity 5 (Trival) : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

I am using f5-payg-autoscale-bigip-ltm.template of f5-aws-cloudformation-5.11.0 .

The CFT is getting rollbacked with below error

BigipAutoscaleGroup - create_failed

Provided Load Balancers may not be valid. Please ensure they exist and try again. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: 651981cf-8f8b-43ad-a59d-76b0076f53ef; Proxy: null)

F5-Autoscale-Test-Deployment - ROLLBACK_IN_PROGRESS

The following resource(s) failed to create: [BigipAutoscaleGroup]. Rollback requested by user.

**Comment by JeffGiroux** [comment]
Do you have the AWS LB created already as part of the pre-req?
