### ISSUE TITLE
App on 443 causes issues

### ISSUE THREAD

**Issue by selhorn** [F5Networks/f5-aws-cloudformation#19]
## Description
The template allows the user to change the virtual server and application pool member ports to 443 or other (rather than 80). When you do this, you can't access the app server through the ELB unless you make manual changes.

Either:
- You should only allow 80
- You should only allow 80 and 443 (and it should work correctly for 443)

If you leave this as a free-form field, the user can enter any number, and I assume a number like 666 wouldn't work. (Although I haven't tested.  : )

Here are the changes required to make 443 work:
1) The pool is using an http monitor. You must change it to https.
2) The virtual server needs an SSL Profile (Client) and SSL Profile (Server).
3) I think *but am not sure* that you should be able to upload a cert.

## Template
F5Networks/f5-aws-cloudformation

## Severity Level
Severity: 2  ?   It doesn't work without this manual workaround.

**Comment by kskoh** [comment]
Yes agree on manual workaround needed if one wants to make a https virtual server on BIG-IP.  But the use case provided by PM is that we are supporting http traffic from ELB to BIG-IPs.  HTTP traffic can be on any other valid TCP port, e.g. 8080 so we have a free-form field.  Close for now.  Bring for internal discussion if further exploration needed.
