### ISSUE TITLE
EC2 instances are ephemeral and meant to be managed by automated processes, not by hand. Is there a way to de-register and re-register without manual hand-holding? 

### ISSUE THREAD

**Issue by forestjohnsonpeoplenet** [F5Networks/f5-aws-cloudformation#20]
## Description

My resident Network Engineer told me that if we have to re-deploy our BYOL F5 virtual edition instance in AWS, it will need to be re-registered. And if we want to use the same registration key, we will have to de-register the old instance first.  He also said that this is a manual process which cannot be automated. 

What options exist to solve this problem?

Can I ...

1. back up the license file after the instance has been licensed, re-create the instance, and restore the license file?
2. Snapshot the instance, stop it, and boot a new image from the snapshot AMI ? 
3. Does F5 provide an API for product deregistration / registration ?

## Template
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/standalone/2nic/f5-existing-stack-byol-2nic-bigip.template

## Severity Level

5

**Comment by smooth-alg** [comment]
License files are tied to the instance. The current options we have for license mobility are UTIL instances available via the Marketplace or License Pools on the central management platform (BIG-IQ) for which there is an API.
ex.
https://devcentral.f5.com/wiki/BIGIQ.HowToSamples_license_initial_activation.ashx
ex. used here:
https://github.com/F5Networks/f5-cloud-libs/blob/develop/lib/bigIpOnboard.js

Also please contact your friendly local account team for assistance with above and other things on the horizon.

**Comment by forestjohnsonpeoplenet** [comment]
Understood.  I believe someone on our side has potentially shot themselves in the foot by choosing BYOL instead of the hourly model. Maybe it was a cost-saving effort. Not sure.

 However, I would argue, its 2017, its entirely reasonable to expect any technology company to provide an API for all processes related to their product. So this is my 2c in the jar for a public de-registration API to go along with the public registration API.

**Comment by jmcalalang** [comment]
@forestjohnsonpeoplenet can you send me your company info for internal tracking, an API call for self releasing a license key has been a RFE, i don't know the timeline, but if/when i find something out I'd be happy to update. j.calalang@f5.com

**Comment by jmcalalang** [comment]
This RFE is in as a product, it was released in version 13.1.X

https://support.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-bigip-ve-13-1-0.html

New in 13.1.0 :: VE
Reusing Licenses
You can now revoke a license from a running instance of BIG-IP VE, and then use that license on another BIG-IP VE.

I haven't dug out the command, however if you do execute it, you should be able to find the string used from /var/log/audit
