### ISSUE TITLE
[WAF Autoscale] Event Logging disabled

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-aws-cloudformation#21]
## Description
After deploying the template, the "Log Profile" setting is not set, thus nothing gets logged to security event logs. 

Logged into BIG-IP GUI and checked Virtual Server > Security > Policies > Log Profile > set to "Disabled"

The Azure template has logging enabled by default, so thought this should be as well. 

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/solutions/autoscale/waf

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by tkam8** [comment]
![image](https://user-images.githubusercontent.com/19481266/28312731-262fcc9e-6bef-11e7-8756-a4ef6ad9b90d.png)

**Comment by kskoh** [comment]
Bug#674736

**Comment by kskoh** [comment]
Resolved in template version 2.4.4 published July 27th, 2017
