### ISSUE TITLE
AWS Cloud Formation GUI doesn't allow templates larger than 450Kb

### ISSUE THREAD

**Issue by IlyaRevich** [F5Networks/f5-aws-cloudformation#23]
## Description
Describe the problem you're having or the enhancement you'd like to request.

From AWS Console-> Template validation error: Template may not exceed 460800 bytes in size.

## Template
For bugs, enter the template with which you are experiencing issues below.
f5-full-stack-across-az-cluster-hourly-2nic-bigip
f5-full-stack-across-az-cluster-byol-2nic-bigip

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by crosbygw** [comment]
[f5-full-stack-across-az-cluster-byol-2nic-bigip.template](https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation/master/experimental/learning-stacks/cluster/2nic/f5-full-stack-across-az-cluster-byol-2nic-bigip.template) is ~ 84k
[f5-full-stack-across-az-cluster-hourly-2nic-bigip.template](https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation/master/experimental/learning-stacks/cluster/2nic/f5-full-stack-across-az-cluster-hourly-2nic-bigip.template) is ~87

I am not able to reproduce this error using these templates. Can you add additional information?

**Comment by crosbygw** [comment]
Webpage for template was downloaded rather then template, clicking "Raw" before saving resolved issue.
