### ISSUE TITLE
S3 BIG-IQ password file incorrect path/file should have more descriptive error

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation#26]
## Description
Running existing or new stack to license with BIG-IQ requires the BIG-IQ password to sit in a file in S3. If the S3 file/location is wrong, then there should be a more descriptive error. Currently, the onboard.log file says something like unable to get credentials. Instead, it should say something like S3 ARN path not found. Or better yet, the AWS CFT stack magic should check that the S3 ARN path exists first prior to kicking off the stack. This would avoid the whole boot up process then inevitable failure if S3 ARN path is wrong for the BIG-IQ password resulting in lack of password knowledge.

If S3 ARN path and permissions are correct, no issues...works great. Can you give a more detailed log other than basically saying that you can't grab the credentials.

To test, launch the stack with a purposely incorrect S3 ARN path. When the VE fails to license and onboarding is done, check onboard.log and you'll see the "can't get credentials" type message. I would like to see that message if indeed it can't get credentials of a valid path/file location. If however the path/file is completely wrong, then it should say something different like "wrong path/file".

## Template
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/standalone/3nic/f5-existing-stack-bigiq-3nic-bigip.template

Other templates using BIG-IQ licensing would probably be affected too.

## Severity Level
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.

**Comment by kskoh** [comment]
Bug#694939

**Comment by kskoh** [comment]
AWS CFT stack is not magical enough to check that the S3 ARN path exists first prior to kicking off the stack.  @seattlevine , can we have a more descriptive error message for when an incorrect S3 ARN path is provided instead of "can't get credentials" type message inside f5-cloud-libs or its aws equivalent.

**Comment by crosbygw** [comment]
Hi Jeff,
An error message was added in cloud-libs-aws (v2.3.0) when there is an invalid s3 bucket.

"Invalid URI. URI should be an S3 arn" 
Closing.

**Comment by jsevedge** [comment]
Test
