### ISSUE TITLE
[LTM Autoscale] failed to create autoscale group

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-aws-cloudformation#29]
## Description
Deployed BYOL CFT but stalls at creation of the autoscale group but eventually fails to create with error: 

"Group did not stabilize... Failed Scaling Activity: In order to use this AWS Marketplace product you need to accept terms and subscribe. 

So something to do with the EULA acceptance, but this normally is automated...Any hints?

## Template

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/solutions/autoscale/ltm

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

![image](https://user-images.githubusercontent.com/19481266/35686776-6ac46588-07b0-11e8-8aaa-e59f6068836e.png)

**Comment by kskoh** [comment]
@tkam8  This is not automated.  Users need to manually accept the EULA on the AWS console for the product that they are trying to use.  This should only occur for the first time if one have not use the product.  Thereafter, the CFT launch should be successful.

**Comment by tkam8** [comment]
@kskoh, thanks for the quick response. My environment was reset so completely forgot about this. 
things also changed up a little bit. When clicking on the F5 instance in the marketplace, a different window shows up, you scroll down and then find 
![image](https://user-images.githubusercontent.com/19481266/35688149-d40a7dfe-07b3-11e8-8889-555edd38632c.png)

and click on the "AWS Marketplace" link and that will take you to the page that you can click on Accept Software Terms...
