### ISSUE TITLE
same-az failover support for partitions 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-aws-cloudformation#32]
seems like same-az failover isn't working when the virtual servers are configured under a different partition than common.
please add support or specify in the documentation that it isn't supported. 

also, please specify in the configuration that a virtual server has to be configured for the failover to work. 
Thanks

**Comment by shyawnkarim** [comment]
Closing. The new [Cloud Failover Extension](https://github.com/f5devcentral/f5-cloud-failover-extension) supports virtual addresses and partitions.
