### ISSUE TITLE
assignment in BIG-IQ license pool not revoked when auto scale instance removed 

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-aws-cloudformation#33]
In a lab setup I am using:
/supported/solutions/autoscale/ltm/f5-bigiq-autoscale-bigip-ltm.template

The assignment of license is working. When a BIG-IP is removed from the auto scaling group its license is not revoked from the BIG-IQ purchased license pool. Based on the BIG-IQ logs, there does not seem to be any failed attempts to remove. On the BIG-IQ, in resstjavad.0.log and restjavad-audit.0.log, there are no logs relating to the removal of the instance. 

As a time reference, this is where the S3 bucket size changed from 2 to 1 in the aws-autoscale.log on the master BIG-IP:

2018-03-28T14:04:04.150Z silly: [pid: 12474] [lib/awsAutoscaleProvider.js] getInstancesFromDb: S3 bucket size: 1

Here is that log file
[aws-autoscale.log](https://github.com/F5Networks/f5-aws-cloudformation/files/1856400/aws-autoscale.log)

I am not exactly clear on how this works, could you give a high level of the events that take place to revoke a license from a BIG-IQ pool?

Let me know if there is some other relevant data I should be looking at in the setup or any other data you would like to see.

**Comment by tthomas0702** [comment]
A detail I forgot to mention:
On the BIG-IQ, the license status for the assignment to the removed instance does change from "Healthy" to "Unhealthy"

**Comment by kskoh** [comment]
This entry in the logfile provided shows an issue.
2018-03-28T14:04:03.923Z debug: [pid: 12474] [lib/autoscaleProvider.js] Can only revoke licenses retrieved from BIG-IQ. Ignoring.

Will analyze further and provide updates. Stay tuned.

**Comment by kskoh** [comment]
BZ#712809

**Comment by kskoh** [comment]
Resolved in Cloud Release v3.0.0 on 04/12/2018
