### ISSUE TITLE
autoscale: regKey pool License not revoked on BIG-IQ when Master BIG-IP terminated 

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-aws-cloudformation#34]
I am using the latest f5-bigiq-autoscale-bigip-ltm.template with a regKey pool that contains only two regKeys.  BIG-IQ version 5.3.0-final.

My autoscaling group only has two members. It is working well to handout and revoke licenses if I terminate the non-master BIG-IPs. But if I terminate the master BIG-IP, it fails to revoke the license on the BIG-IQ. I do not see any logs about an attempt on the BIG-IQ. 

Here is a run through what I am doing:

At the start the Master BIG-IP is "i-09f3a3736d449b6dc".

Below is the s3 instances files contents showing who is master before I terminate the master:

{
  "privateIp": "10.0.2.5",	<-- i-0114d988efc79a4c5 non-master
  "mgmtIp": "10.0.2.5",
  "hostname": "ip-10-0-2-5.us-west-2.compute.internal",
  "isMaster": false,
  "providerVisible": true,
  "status": "OK",
  "lastUpdate": "2018-04-06T22:50:05.308Z",
  "masterStatus": {
    "instanceId": "i-09f3a3736d449b6dc",
    "status": "OK",
    "lastUpdate": "2018-04-06T22:50:05.118Z",
    "lastStatusChange": "2018-04-06T22:14:27.219Z"
  },
  "lastJoinRequest": "2018-04-06T22:50:05.305Z"
}
{
  "privateIp": "10.0.2.153",   <- i-09f3a3736d449b6dc Master
  "mgmtIp": "10.0.2.153",
  "hostname": "ip-10-0-2-153.us-west-2.compute.internal",
  "isMaster": true,
  "providerVisible": true,
  "status": "OK",
  "lastUpdate": "2018-04-06T22:50:04.157Z",
  "masterStatus": {
    "instanceId": "i-09f3a3736d449b6dc",
    "status": "OK",
    "lastUpdate": "2018-04-06T22:50:04.156Z",
    "lastStatusChange": "2018-04-06T22:02:04.192Z"
  }
}

Then I terminate i-09f3a3736d449b6dc. 
For reference in the /var/log/cloud/aws/aws-autoscale.log I did this about 2018-04-06T22:57:25

On remaining instance:
2018-04-06T23:02:04.159Z info: [pid: 19086] [scripts/autoscale.js] No master ID found.

The new instance finished launching before the license was not revoked, so there was no license for it since pool only had two.
I mention this so you can understand the time of BIG-IQ log below in case it is useful.

On BIG-IQ:
INFO][06 Apr 2018 16:03:55 PDT][/shared/authn/login AuthnWorker] User admin successfully logged in from 10.0.2.213 using the local authentication provider.
[WARN][06 Apr 2018 16:03:55 PDT][/cm/device/tasks/licensing/pool/member-management/cb1b3ba9-c727-4e37-a85e-0f695616edf4/worker DeviceLicensingAssignmentTaskWorker] Task failed at step VALIDATE_LICENSE with message: 2 offerings found for regkey pool license 'mcnair_regkey' and the given search criteria (none), but none are available for use

At this point the former non-master, i-0114d988efc79a4c5, is master but the old master that I terminated did not get it's license revoked. The new instance that spun up could not get a license because there were none available. 

Here is the current status of the s3 instance files:

{
  "privateIp": "10.0.2.5",  <- new master i-0114d988efc79a4c5
  "mgmtIp": "10.0.2.5",
  "hostname": "ip-10-0-2-5.us-west-2.compute.internal",
  "isMaster": true,
  "providerVisible": true,
  "status": "OK",
  "lastUpdate": "2018-04-06T23:04:05.209Z",
  "masterStatus": {
    "instanceId": "i-0114d988efc79a4c5",
    "status": "OK",
    "lastUpdate": "2018-04-06T23:04:04.465Z",
    "lastStatusChange": "2018-04-06T23:04:04.465Z"
  },
  "lastJoinRequest": "2018-04-06T22:56:04.470Z"
}
{
  "privateIp": "10.0.2.213",  <- new instance, no license
  "mgmtIp": "10.0.2.213",
  "hostname": "ip-10-0-2-213.us-west-2.compute.internal",
  "isMaster": false,
  "providerVisible": true,
  "status": "OK",
  "lastUpdate": "2018-04-06T23:04:11.360Z",
  "masterStatus": {
    "instanceId": "i-0114d988efc79a4c5",
    "status": "OK",
    "lastUpdate": "2018-04-06T23:04:07.930Z",
    "lastStatusChange": "2018-04-06T23:04:07.930Z"
  },
  "lastJoinRequest": "2018-04-06T23:04:11.359Z"
}

So the issue is that if the master BIG-IP is terminated, the license for the master does not get revoked. 
There were no further logs on the BIG-IQ after the ones I posted above. It's been about 30 minutes.

I am attaching the log aws-autoscale.log from the new master BIG-IP.
[aws-autoscale.log](https://github.com/F5Networks/f5-aws-cloudformation/files/1885859/aws-autoscale.log)

**Comment by kskoh** [comment]
How soon did the other new unit come up after the master was terminated?

**Comment by tthomas0702** [comment]
2018-04-06T22:57:25 UTC        <-- Terminated the master

06 Apr 2018 16:03:55 PDT        <-- New instance requests license from BIG-IQ
* In UTC is 23:03:55 UTC        =      6 minutes and 30 seconds


The new, non-master instance was up and requested a license in 6 min 30 sec.

**Comment by tthomas0702** [comment]
### I tested with version 3.0.0. When I terminate the master the license for that instance did not get revoked. 

	i-0aa9d72b9e7abb864 was the master deleted. 

	i-06104ed74ae900fb7 is the remaining peer that got promoted to master. 

### Both of the above instances were up and running more than 30 minutes prior to deleting the master. 

### One thing I noticed, when the instance was promoted to master the BIG-IQ started to log auth errors about it. 
/var/log/restjavad.0.log:
------------------------
[INFO][13 Apr 2018 11:38:04 PDT][/shared/authn/login AuthnWorker] User admin failed to login from 10.0.2.143 using the local authentication provider
[INFO][13 Apr 2018 11:38:09 PDT][/shared/authn/login AuthnWorker] User admin failed to login from 10.0.2.143 using the local authentication provider
[INFO][13 Apr 2018 11:38:14 PDT][/shared/authn/login AuthnWorker] User admin failed to login from 10.0.2.143 using the local authentication provider


For reference this is a snippet from the new master aws-autoscale.log to show when it became master:
aws-autoscale.log:
-----------------
2018-04-13T18:36:05.266Z info:  Determining master instance id.
2018-04-13T18:36:05.357Z info:  master has been disconnected for too long ( 120202 ms )
2018-04-13T18:36:05.358Z info:  Old master no longer valid: master is expired
2018-04-13T18:36:05.359Z info:  Electing master.
2018-04-13T18:36:05.360Z info:  Using master ID: i-06104ed74ae900fb7   <-- this is the new master 10.0.2.143
2018-04-13T18:36:05.360Z info:  This instance is master
2018-04-13T18:36:05.360Z info:  New master elected
2018-04-13T18:36:05.468Z info:  Becoming master.


### I am attaching the aws-autoscale.log from the new master and restjavad.0.log from BIG-IQ.

Logs
[aws-autoscale.log](https://github.com/F5Networks/f5-aws-cloudformation/files/1908882/aws-autoscale.log)


[restjavad.0.log](https://github.com/F5Networks/f5-aws-cloudformation/files/1908885/restjavad.0.log)

**Comment by kskoh** [comment]
Reproduce and RCA on "User admin failed to login from 10.0.2.143 using the local authentication provider"

**Comment by kskoh** [comment]
Unable to reproduce.  Will contact engineer to work thru issues.
