### ISSUE TITLE
Unrecognized EC2 action DescribeNetworkInterfaceAttributes

### ISSUE THREAD

**Issue by silliw-nhoj** [F5Networks/f5-aws-cloudformation#37]
Hi,

The EC2 action DescribeNetworkInterfaceAttributes is unrecognized. It should be DescribeNetworkInterfaceAttribute (singular).

Thanks,
John

**Comment by kskoh** [comment]
Which specific CFT are you referring to?

**Comment by silliw-nhoj** [comment]
The ec2 action exists in the cluster, autoscale, and standalone CFTs under
f5-aws-cloudformation/supported/

When the CFT is deployed, there is a warning that states the action is unrecognized. Changing the action name to a singular name DescribeNetworkInterfaceAttribute gets rid of the warning.

**Comment by shyawnkarim** [comment]
Closing. [Cloud Failover Extension](https://github.com/f5devcentral/f5-cloud-failover-extension) now handles all failover functionality.
