### ISSUE TITLE
use ACM cert ?

### ISSUE THREAD

**Issue by bwolmarans** [F5Networks/f5-aws-cloudformation#38]
Is it possible for the SSL Cert field to accept the ACM Cert instead of the IAM cert format?

**Comment by kskoh** [comment]
Which specific CFT are you referring to?

**Comment by bwolmarans** [comment]
Hi I am referring to this one
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/experimental/learning-stacks/solutions/autoscale/waf

**Comment by shyawnkarim** [comment]
Closing. Templates now support AS3 declarations, which handle SSL certs.
