### ISSUE TITLE
ALB cannot be used innplace of ELB

### ISSUE THREAD

**Issue by joeranallo** [F5Networks/f5-aws-cloudformation#41]
I was not able to utilize an ALB when specifying my external load balancer for the WAF hourly template. Is this supported or can it be added as a feature in the future?

**Comment by joeranallo** [comment]
Do you have plans to support ALB and if so do you have a rough target date? Thanks for the quick reply!

**Comment by kskoh** [comment]
Are you currently a F5 product user and have a representative from F5 you are working with in deployment? If so, I can speak with your F5 Sales engineer to determine the case and can provide you further updates.

**Comment by ttranx** [comment]
joeranallo, can you help us understand the use case for ALB?

**Comment by joeranallo** [comment]
Http/2

**Comment by shyawnkarim** [comment]
This enhancement request is being tracked internally with ESECLDTPLT-2053.
