### ISSUE TITLE
deploy/README.md quickstart links are broken

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-aws-cloudformation#42]
404:
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/experimental/full-stack-byol-1nic-bigip.template

perhaps the correct URL?
https://github.com/F5Networks/f5-aws-cloudformation/blob/master/experimental/standalone/1nic/learning-stack/byol/f5-full-stack-byol-1nic-bigip.template

**Comment by crosbygw** [comment]
link corrected.
