### ISSUE TITLE
links to full-stack templates

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-aws-cloudformation#43]
I don't see a supported CFT that builds a new stack. 

For example, supported/standalone/1nic has only "existing-stack" or "production-stack" but no "learning-stack" or "full-stack". 

I think it would be nice to add a README.md in supported/standalone/1nic that explains that there is an experimental template in experimental/standalone/1nic for "full-stack" deployment.

**Comment by shyawnkarim** [comment]
This document enhancement request is being tracked internally with ID ESECLDTPLT-2054. Thanks for your feedback.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2)

These V2 templates offer both new stack and existing stack deployment options.
