### ISSUE TITLE
Can't assign HA ip for F5 in 2nd AZ

### ISSUE THREAD

**Issue by fitchxlin** [F5Networks/f5-aws-cloudformation#44]
I deployed F5 across 2 AZs using your cloud formation template of 3 nics.  However, when it comes to create HA, I can't assign the HA IP for the 2nd F5 in different AZ.  What's the workaround?

**Comment by MrVJTod** [comment]
not sure what you did or what's not working

just looking at the external NICs, where you'd attach the HA IPs

box1-external
only-self-ip : 10.1.1.1
default public : 52.52.52.52
ha IP : 10.1.1.4

box2-external
only-self-ip : 10.2.2.2
default public : 54.54.54.54
ha IP : 10.2.2.4

HA public : 35.35.35.35

The HA public will automatically get assigned to either HA public IP. This is an automatic part of the failover. You can't attach this IP to both boxes at the same time.

**Comment by fitchxlin** [comment]
The HAs are in different subnets, how are we ensure they have communication?  I followed the instructions https://clouddocs.f5.com/cloud/public/v1/aws/AWS_ha.html#high-availability-networking-objects to setup trust but not able to find the peer device.

**Comment by MrVJTod** [comment]
The only time I've seen nodes unable to communicate with each other is if the Default Route is never setup in the LOCAL_ONLY partition
https://www.f5.com/pdf/deployment-guides/f5-aws-ha-dg.pdf

I've only worked with v12 nodes. I'm not sure if anything is different with v13.
What version are you using?

**Comment by fitchxlin** [comment]
nevermind, i figured it out.

**Comment by MrVJTod** [comment]
What was your fix? I'd guess that you had your public IP addresses listed here. But each box should only have it's local 10.* IP address on this page, and instead of putting them in the None group, all mine are in the traffic group "traffic-group-local-only"

**Comment by jagibson** [comment]
I'm also having this problem.  What was the fix?

[](https://xkcd.com/979/)
