### ISSUE TITLE
aws ec2 instance create failed due to "OptInRequired"

### ISSUE THREAD

**Issue by aheilmaier** [F5Networks/f5-aws-cloudformation#45]
I tried to deploy the 3-nic template with existing  vpc and subnets:
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/3nic

Due to following error a rollback was done:
In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=8esk90vx7v713sa0muq2skw3j (Service: AmazonEC2; Status Code: 401; Error Code: OptInRequired; Request ID: 42042966-8757-4e1e-a4fe-4b7942b36816)

Bigip1Instance AWS::EC2::Instance

From the error message it seems that the Bigip Instance needs to ack the license. 
Is there a way to ack such a problem with in the cloudformation template ?

**Comment by MrVJTod** [comment]
you shouldn't have to do that as part of your cloudformation.
have you accepted the terms manually from the marketplace? that's all that should be required to allow your automation to consume the marketplace objects.

**Comment by aheilmaier** [comment]
o.k. Thank's. I got it.
I have you accepted the terms manually from the marketplace.
I needed to follow the link in the error message and need to subscribe.
