### ISSUE TITLE
Same az cluster deployment creates failover group called across_az_failover_group

### ISSUE THREAD

**Issue by bodra-swift** [F5Networks/f5-aws-cloudformation#46]
A per the title all the templates under the following branch create a failover group with a confusing name:
f5-aws-cloudformation/supported/failover/same-net/via-api/

The failover group is created as 'across_az_failover_group' even though this is a 'same az' deployment

**Comment by kskoh** [comment]
Thank you for the feedback. Tracking this as bug# 741896.  Will update this issue when we roll the fix out in a future release.

**Comment by crosbygw** [comment]
Same az templates now use device group same_az_failover_group beginning in [release 4.2.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v4.2.0).

Thank you for your feedback.
