### ISSUE TITLE
Timezone value in docs

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-aws-cloudformation#47]
Hi,  

It's somewhat unclear which exact values are legal for the `timezone` parameter in templates.
The default `UTC` is confusing.  

Moreover, the template accepts illegal values like `UTC+3` or `IL`, and the deployment succeeds, however the BIG-IP is unlicensed due to:

```
2018-08-28T19:51:02.659Z error:  Onboard failed: 01070920:3: Application error for confpp: UTC+3 is not a valid time zone.
```

We could potentially link to:
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
referencing the `TZ*` column and list some examples like `US/Eastern` or `Europe/Bratislava`.

Thanks!

**Comment by kskoh** [comment]
Thank you for the feedback and suggestion. Tracking this as bug# 741960 to work with docs team. Will update this issue when we roll the fix out in a future release.

**Comment by crosbygw** [comment]
We have added additional timezone information and guidence in the parameter description in template [release v4.2.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v4.2.0)
Thanks again for your feedback.
