### ISSUE TITLE
AWS ELB shows outofservice due to failing health checks

### ISSUE THREAD

**Issue by agnnn** [F5Networks/f5-aws-cloudformation#48]
I deployed the CFT autoscaling template and it was successful with no issues. But when I create a classical ELB with BIGIP instances as targets, the ELB health check(configured to ping TCP:443) shows the instances are out of service. 
Is there anything else, I should be changing in the template or on the BIG IP itself ??

**Comment by kskoh** [comment]
Hi @agnnn, which particular autoscale CFT was deployed?  Please provide the link to it.
Do you have a port 443 VS on the BIG-IP instance?  Or is it a port 80 VS?

**Comment by agnnn** [comment]
Here is the link to the template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/payg

Yes i do have VS listining on port 443.

**Comment by kskoh** [comment]
If healthcheck is failing on ELB, one would check the communication between the ELB and BIG-IP to port 443.  This might need further troubleshooting such as gathering ingress traffic from BIG-IP instance.  For better assistance, please open an official support case with the world class [F5 Support team](https://www.f5.com/services/support) on the reported issue of your autoscale WAF deployment.

**Comment by kskoh** [comment]
Take note from [Prerequisites](https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/payg#prerequisites) section of the README:
"
The classic ELB in front of the BIG-IP VEs must be preconfigured to perform SSL offload for the BIG-IP WAF auto scale tier. See ELB configuration for an example of the ELB configuration.
"

**Comment by kskoh** [comment]
If there are any deployment issues, please kindly open an official support case with F5 Support team for better assistance and tracking.
