### ISSUE TITLE
Source address parameters don't accept lists

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-aws-cloudformation#49]
Hi,
  
The `restrictedSrcAddress` and `restrictedSrcAddressApp` template parameters don't seem to accept lists:

```
Error: aws_cloudformation_stack.main: parameters (restrictedSrcAddress): '' expected type 'string', got unconvertible type '[]interface {}'
```
  
```
Error: aws_cloudformation_stack.main: parameters (restrictedSrcAddressApp): '' expected type 'string', got unconvertible type '[]interface {}'
```

So it's unclear if (and how) we can specify **multiple** ranges of allowed source IP addresses.

I used `f5-existing-stack-byol-3nic-bigip.template`, but I imagine other templates have the same issue.

Thanks!

**Comment by kskoh** [comment]
Known issue cannot accept lists at this time.  Tracking as BZ#742089.  Will be a great improvement.  Updates will be performed on that BZ# as progress is made.  Please follow internal or for public please contact F5 Support for status on BZ#.  Closing.
