### ISSUE TITLE
BucketNotEmpty at stack delete failure

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-aws-cloudformation#52]
Hi,

Trying to delete a CF stack based on a successfully deployed `f5-existing-stack-across-az-cluster-byol-3nic-bigip.template` fails with the following error message:

```
* aws_cloudformation_stack.bigip (destroy): 1 error(s) occurred:

* aws_cloudformation_stack.bigip: DELETE_FAILED: ["The following resource(s) failed to delete: [S3Bucket]. " "The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; 
```

Not sure if this is an expected behaviour.

Deleting the bucket's contents manually - solves the issue, and stack delete succeeds.

Thanks!

**Comment by ArtiomL** [comment]
Also, `f5-existing-stack-same-az-cluster-byol-3nic-bigip.template` has the same issue.

Thanks.

**Comment by kskoh** [comment]
It is expected behavior.  AWS thing.  S3 bucket needs to be empty for bucket to be able to be deleted from stack level.
