### ISSUE TITLE
Option to install AS3

### ISSUE THREAD

**Issue by ArtiomL** [F5Networks/f5-aws-cloudformation#53]
Hi,

Would it be possible to add an optional, boolean parameter to the CFTs - to install the latest AS3 version on the instances after stack deployment?

I'm currently using this: https://github.com/ArtiomL/f5networks/blob/master/scripts/instas3.sh

This would help with automating the actual BIG-IP config post-deployment, without the need to manually install AS3.

Thanks!

**Comment by ArtiomL** [comment]
@nmenant, @jmcalalang - thoughts?

**Comment by kskoh** [comment]
Sounds like a good idea.  I will try find time to check out ArtiomL work.

**Comment by ArtiomL** [comment]
Turns out there is a section for custom config:

```
"### START CUSTOM CONFIGURTION\n",
"### END CUSTOM CONFIGURATION"
```

**Comment by crosbygw** [comment]
As of release v4.1.2 all templates automatically install latest stable version of as3 and include parameter to add url for a as3 deceleration to use during initial onboarding.
