### ISSUE TITLE
/config/cloud/aws/run_autoscale_backup.sh has formatting error

### ISSUE THREAD

**Issue by panama63119** [F5Networks/f5-aws-cloudformation#54]
S3 backup script is not running successfully. This is the error when run:

18-09-21T15:25:34.031Z info:  This instance is master 
2018-09-21T15:25:34.393Z warn:  Unknown cluster action backup-ucs--log-level 
2018-09-21T15:25:34.394Z error:  autoscaling error: Unknown cluster action backup-ucs--log-level 

 There is "space" missing between the option that specifies backup-ucs and the next option log-level. 

This is from the script on the F5 ASM after deployment:

--cluster-action backup-ucs--log-level silly

**Comment by kskoh** [comment]
Thank you for bring to our attention.  Bug tracked as:
ESECLDTPLT-634 AWS: Missing a space between options in run_autoscale_backup.sh

**Comment by crosbygw** [comment]
syntax corrected in run_autoscale_backup.sh.
