### ISSUE TITLE
Application persistence with client cert auth

### ISSUE THREAD

**Issue by mototwister** [F5Networks/f5-aws-cloudformation#56]
Hi. I need your assistance about application persistence with client cert auth.

I am interested in using the following template:
Auto scaling the BIG-IP VE Local Traffic Manager (LTM) in AWS: Existing Stack with BIG-IQ Licensing (Frontend via ELB)

If using TCP listener, sticky session is not available. It means that BIG-IP's persistence is not available as well. However, client cert auth is available.

If using HTTPS listener, sticky session is available, but CLB has to re-encrypt the traffic for client cert auth with BIG-IP, so server cert/key has to be registered in CLB setting. However, I cannot find any server key setting in CLB.

I was wondering what is the best way to use client cert auth using the above template?

Thank you.

**Comment by kskoh** [comment]
Internal F5 Sales
