### ISSUE TITLE
WAF and LTM autoscale via DNS fail with custom-config.log showing autoscaling error: providerOptions.poolName is required

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation#57]
I'm trying to deploy the autoscale templates with DNS. The F5 devices look to be properly provisioned, licensed, and clustered. However, they never show up as GSLB pool members on my BIG-IP DNS box. When I login to the new F5 autoscale devices via CLI, I checked logs.

[admin@ip-10-0-11-18:Active:Standalone] ~ # cat /var/log/cloud/aws/custom-config.log | grep error
2018-10-28T22:04:44.074Z error: [pid: 25199] [scripts/autoscale.js] autoscaling error: providerOptions.poolName is required 

When comparing the template, there is no parameter called provderOptions.poolName. There however a parameter called dnsProviderPool. Is the autoscale.js script looking for the wrong parameter name?

I know my GTM box is working fine because I can successfully run the Azure autoscale DNS templates, point to the same autoscale_pool name, target GTM boxes, etc. Something is throwing the autoscale.js error in the AWS templates.

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-dns/1nic/existing-stack/bigiq

same issue for ltm templates too

**Comment by kskoh** [comment]
Thanks for the feedback.  Will look and update with more info

**Comment by shyawnkarim** [comment]
Status undetermined; closing due to age. Please reopen if still an issue.
