### ISSUE TITLE
BIGIQ deployment not complete 

### ISSUE THREAD

**Issue by yossi-r** [F5Networks/f5-aws-cloudformation#58]
## Description
I'm deploying using the https://github.com/F5Networks/f5-aws-cloudformation/tree/master/experimental/bigiq/licenseManagement/standalone/2nic/existing-stack/byol
template. 

after the template completes, i login to the BIGIQ and under "this device" --> "general properties" , no parameters are populated. 
on restjavad.0.log i get the following messages:

[INFO][11 Dec 2018 13:32:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured
[INFO][11 Dec 2018 13:33:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured
[INFO][11 Dec 2018 13:34:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured
[INFO][11 Dec 2018 13:35:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured
[INFO][11 Dec 2018 13:35:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured
[INFO][11 Dec 2018 13:36:34 PST][/cm/shared/event/analyzer EventAnalyzer] The machineIdResolver failed to find the localhost, this usually happens before the discovery address has been set or right after a restart. Event Analysis cannot start until it has been configured

if i manually go to /ui/setup and click 'next' without changing any of the values the log messages stop and the properties show up on the device information. 

## Template
f5-existing-stack-byol-2nic-bigiq-licmgmt.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

2

**Comment by f5-gasingh** [comment]
Hello @yossi-r, thank you for reporting this issue. We are tracking this issue internally with bug id -813.

**Comment by garrettdieckmann** [comment]
Hi @yossi-r - This issue has been resolved, and released in our most recent CFTs, v4.1.4.

Link to BIG-IQ template: https://github.com/F5Networks/f5-aws-cloudformation/blob/v4.1.4/experimental/bigiq/licenseManagement/standalone/2nic/existing-stack/byol/f5-existing-stack-byol-2nic-bigiq-licmgmt.template

Thanks!
