### ISSUE TITLE
Provide option in CFTs to alter image volume size

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-aws-cloudformation#59]
## Description
Describe the problem you're having or the enhancement you'd like to request.

The present supported CFTs default to a fixed volume size of (I think) 30Gb.  For some applications, this is not sufficient.  Provide an option to make VolumeSize a parameter.  We've manually altered the template with a static value, but would like to see it in the supported template.

## Template
For bugs, enter the template with which you are experiencing issues below.

f5-existing-stack-across-az-cluster-byol-3nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
3
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by f5-gasingh** [comment]
This issue was resolved through F5 support.

**Comment by C0missar** [comment]
No, it was not resolved by F5 support.  They told me to open an issue here.
