### ISSUE TITLE
[BIG-IQ] experimental docs

### ISSUE THREAD

**Issue by tkam8** [F5Networks/f5-aws-cloudformation#64]
## Description

Doc errata in below readme file for BIG-IQ CFT. There is no automatic failover AFAIK, and no real shifting of public traffic, even if this is referring to control plane traffic.

https://github.com/F5Networks/f5-aws-cloudformation/blob/ada5cd3a9d78ce40f404e020edf9245a22a30e30/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/README.md

Errata:
"The BIG-IQ VE can detect Availability Zone failure and automatically shift public traffic to the BIG-IQ in the Availability Zone that is unaffected."

Suggested Fix:
In a BIG-IQ high availability configuration, the BIG-IQ system replicates configuration changes since the last synchronization from the primary device to the secondary device every 30 seconds. If it ever becomes necessary, you can have the secondary peer take over management of the BIG-IP devices.

This is taken straight from askF5:
https://support.f5.com/kb/en-us/products/big-iq-centralized-mgmt/manuals/product/big-iq-centralized-management-plan-implement-deploy-6-1-0/04.html#guid-89348602-0f86-4b77-b905-393f0b2c554b

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/ada5cd3a9d78ce40f404e020edf9245a22a30e30/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol

## Severity Level

Severity: 5

**Comment by crosbygw** [comment]
tkam8, thanks for the notes, I will submit an internal request for the documentation change. This is been tracked internally as issue #920.

**Comment by crosbygw** [comment]
Document corrected with release [v4.1.4](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v4.1.4)
