### ISSUE TITLE
Parameter passing to CFT via Ansible inconsistent

### ISSUE THREAD

**Issue by C0missar** [F5Networks/f5-aws-cloudformation#66]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

No

## Description
Describe the problem you're having or the enhancement you'd like to request.

When calling CFTs via Ansible, some string parameters must be specified within quotes, and others must not be.  This includes blank values.
When not including values, some parameters may be omitted and they will receive the default, but if included, cannot be blank.  Blank values should be treated the same as omitted values.

AllowUsageAnalytics MUST be in quotes, i.e. "No"
customImageId must NOT be in quotes, and a blank field is not acceptable (min length is 1); a blank value would make more sense than the value "OPTIONAL", which is not a AMI ID
restrictedSrcAddress and restrictedSrcAddressApp must NOT be in quotes, i.e. 10.0.0.0/8; if "10.0.0.0/8" is entered, the quotes will be embedded in the device configuration (without error msg), and IP address comparisons will fail, rendering the device inaccessible.
restrictedSrcAddress and restrictedSrcAddressApp only accept a single CIDR, although the tmsh value allows a string with a series of CIDRs separated by spaces

## Template
For bugs, enter the template with which you are experiencing issues below.

All, but the example I've been working with mostly is f5-prod-stack-across-az-cluster-byol-3nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Hi, sorry for the long delay in response.

We have created internal issue 1057 to track this improvement, and will post back here when it is done.
thanks

**Comment by C0missar** [comment]
Great, thank you!


Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com

http://www.sherwin-williams.com



-----"Mike Shimkus" <notifications@github.com> wrote: -----
To: "F5Networks/f5-aws-cloudformation" <f5-aws-cloudformation@noreply.github.com>

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

If this feature is still important to you, please submit an issue in the V2 repo.
