### ISSUE TITLE
Template validation error: S3 error: Access Denied 

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-aws-cloudformation#68]
## Do you already have an issue opened with F5 support?
no

## Description
When trying to use the template I am getting the error:

Template validation error: S3 error: Access Denied 

## Template
I have tried a few and getting the same with all. tried in us-west-2 and us-east-1
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=F5-PAYG-BIGIP-LTM-Autoscale&templateURL=https:%2F%2Fs3.amazonaws.com%2Ff5-cft%2Ff5-payg-autoscale-bigip-ltm.template

## Severity Level
2

**Comment by edwoodjrjr** [comment]
Hi, does your account have the right to create IAM roles, and did you check the box to acknowledge that cloudformation may create IAM roles on the "Create" page?

**Comment by chen23** [comment]
I'm also seeing access denied when deploying:

![image](https://user-images.githubusercontent.com/63689/52575406-26eb5700-2dec-11e9-9d8b-203bcc99cebe.png)

https://s3.amazonaws.com/f5-cft/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template

**Comment by edwoodjrjr** [comment]
No issues for me in us-east-1.  Are you seeing this every time?  Can you provide template inputs?

**Comment by chen23** [comment]
it's not getting past loading the template: 

```
 curl -v https://s3.amazonaws.com/f5-cft/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template
* About to connect() to s3.amazonaws.com port 443 (#0)
*   Trying 52.216.129.93...
* Connected to s3.amazonaws.com (52.216.129.93) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=s3.amazonaws.com,O=Amazon.com Inc.,L=Seattle,ST=Washington,C=US
*       start date: Dec 03 00:00:00 2018 GMT
*       expire date: Oct 25 12:00:00 2019 GMT
*       common name: s3.amazonaws.com
*       issuer: CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US
> GET /f5-cft/f5-existing-stack-across-az-cluster-payg-3nic-bigip.template HTTP/1.1
> User-Agent: curl/7.29.0
> Host: s3.amazonaws.com
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< x-amz-request-id: F0DDE3F0BAD510D6
< x-amz-id-2: /xm4cG3qQwNgnwljmqtBQu9gqql/VuvlkxgdiKpzUEY4xr/brqbeaE+C5dbtFgTJHJqooPW1RFk=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 11 Feb 2019 17:13:36 GMT
< Server: AmazonS3
<
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host s3.amazonaws.com left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F0DDE3F0BAD510D6</RequestId><HostId>/xm4cG3qQwNgnwljmqtBQu9gqql/VuvlkxgdiKpzUEY4xr/brqbeaE+C5dbtFgTJHJqooPW1RFk=</HostId></Error>
```

**Comment by edwoodjrjr** [comment]
I see.  I just made a change, can you try it again?

**Comment by chen23** [comment]
looks like that resolved the permission error.  i only spot checked two templates.

![image](https://user-images.githubusercontent.com/63689/52581458-cf071d00-2df8-11e9-8462-c95ed22b1baf.png)

**Comment by edwoodjrjr** [comment]
Looks like the templates we released last week didn't get set to public in the bucket.  I updated all of them so should be good now.

**Comment by tthomas0702** [comment]
That has resolved it for me as well. I Just deployed in us-west-2 without hitting the permissions error.
