### ISSUE TITLE
Launch button links are incorrect

### ISSUE THREAD

**Issue by edwoodjrjr** [F5Networks/f5-aws-cloudformation#69]
## Do you already have an issue opened with F5 support?
No

## Description
Launch button links for Autoscale WAF w/ELB, Autoscale WAF w/NLB, and BIG-IQ LTM Autoscale are broken; verify.

## Template
Autoscale WAF w/ELB
Autoscale WAF w/NLB
BIG-IQ Autoscale

## Severity Level
4

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by edwoodjrjr** [comment]
Tracking with internal issue 995.

**Comment by crosbygw** [comment]
corrected in release latest release: https://github.com/F5Networks/f5-aws-cloudformation/tree/v4.1.4
