### ISSUE TITLE
license_from_bigiq.sh called from wrong directory

### ISSUE THREAD

**Issue by dabungis** [F5Networks/f5-aws-cloudformation#7]
I tested a few templates and noticed failures. When I checked logs, I get this...

2016-12-10T01:05:39.720Z - info: start install biqiq license
2016-12-10T01:05:39.720Z - error: /config/cloud/aws/custom-config.sh: line 11: /config/cloud/aws/license_from_bigiq.sh: No such file o r directory

However, the CFT places that shell file in /tmp like below...

                            "/tmp/license_from_bigiq.sh": {
                                "group": "root",
                                "mode": "000755",
                                "owner": "root",
                                "source": "http://cdn.f5.com/product/templates/utils/license_from_bigiq_v5.0.sh"

As a result, the following license line fails because the script is called from the wrong directory.

                                            "echo 'start install biqiq license'\n",
                                            ". /config/cloud/aws/license_from_bigiq.sh\n",

**Comment by NojanMoshiri** [comment]
Which template where you using?

**Comment by seattlevine** [comment]
That shows up in many of the experimental templates - looks like something we need to fix in the build script.

**Comment by crosbygw** [comment]
Modified cft big-iq scripts to use correct directory.
