### ISSUE TITLE
Incorrect Instance Type map in CFTs

### ISSUE THREAD

**Issue by hparr** [F5Networks/f5-aws-cloudformation#70]
## Do you already have an issue opened with F5 support?
No

## Description
CFT template instance type validations are not inling with supported instance types on Clouddocs.f5.com.  For example the t2 instances are missing. 

## Template
Confimred on singleNic PayG exiting stack. 

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 4 ** :  This can impact preferred deployment form factor.

**Comment by namhly** [comment]
Thank you. We're tracking with internal issue 1058

**Comment by shyawnkarim** [comment]
Closing. Instance types, in the templates, are sometimes subsets of supported instance types.
