### ISSUE TITLE
BIG-IQ LM Template v4.1.3 uses old AMI for GovCloud

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-aws-cloudformation#72]
## Do you already have an issue opened with F5 support?
No this is a feature request

## Description
Template does not use latest AMI

**Currently utilizes 6.0.1.0.0.813**

			"us-gov-west-1": {
			  "Best": "ami-74d64915"
			}

**Should use 6.1.0.0.0.1224**

ami-29d4b548

## Template
https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation/master/experimental/bigiq/licenseManagement/cluster/2nic/existing-stack/byol/f5-existing-stack-cluster-byol-2nic-bigiq-licmgmt.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Tracking: @aknot242

**Comment by wduongf5** [comment]
Hi Jon,

Thanks for filing the issue. I've created an internal tracking number 1159 for it.

**Comment by shyawnkarim** [comment]
Closing. This issue is being addressed and will be in the next release. Target =~ April 23, 2020.
