### ISSUE TITLE
Clarify requirement for internet access in existing template

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-aws-cloudformation#75]
## Do you already have an issue opened with F5 support?
No
## Description

Currently if you do not have public internet access the deployment will fail.  Please make it more prominent that this is the case. (i.e. say make sure you have a NAT GW if you say "No")

![bad-input](https://user-images.githubusercontent.com/63689/62786529-c8e4b700-ba90-11e9-8b65-68376cf77935.png)

## Template
For bugs, enter the template with which you are experiencing issues below.

https://github.com/F5Networks/f5-aws-cloudformation/blob/master/supported/failover/same-net/via-api/3nic/existing-stack/payg/f5-existing-stack-same-az-cluster-payg-3nic-bigip.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for taking the time to submit this issue. I've created an issue in Jira (#1589) for it.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

Our V2 READMEs provide guidance around this.
