### ISSUE TITLE
Incorrect description of subnet for ClusteredBIG-IPVE-3NICs-AcrossAZ-PAYG

### ISSUE THREAD

**Issue by yom-ops** [F5Networks/f5-aws-cloudformation#77]
## Do you already have an issue opened with F5 support?
no

## Description
There is a typo in the table where CFT options are described

## Template
ClusteredBIG-IPVE-3NICs-AcrossAZ-PAYG

## Severity Level
Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. I've created internal issue ESECLDTPLT-1971 to get this documentation fixed.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

Our documentation has been completely redone for V2.
