### ISSUE TITLE
Yellow launch button from within github results in S3 access denied in CFT

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation#79]
## Do you already have an issue opened with F5 support?
no

## Description
Initial screen upon CFT template load results an S3 access error when using the yellow launch button from within github. I can’t proceed past this initial screen. The workaround is to upload the template file on the CFT screen. See more info and repro steps below.

This is what I’m doing (and always have done)…
1.	Logged into AWS console already
2.	Visit github templates page, choose F5 template, hit yellow launch button
3.	New AWS tab opens with your logged in credentials going to CloudFormation
4.	Template loads in initial screen
5.	Hit next
6.	Fill in CFT values, submit

But now the flow is…
1.	Logged into AWS console already
2.	Visit github templates page, choose F5 template, hit yellow launch button
3.	New AWS tab opens with your logged in credentials going to CloudFormation
4.	Template loads in initial screen
5.	Hitting Next results in S3 error.

Workaround…
If I upload a template file on the screenshot below then it works. However, if I click the “Launch” yellow button from within the github template, then S3 error.

S3 error = see pic below, when clicking on yellow launch github button…
“S3 error: Access Denied”
S3 URL (loaded by default) = https://s3.amazonaws.com/f5-cft/f5-existing-stack-payg-2nic-bigip.template 

Uploading file manually
Pull down raw = https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation/master/supported/standalone/2nic/existing-stack/payg/f5-existing-stack-payg-2nic-bigip.template
Upload in CFT wizard screen.
Resulting URL = S3 URL: https://s3-external-1.amazonaws.com/cf-templates-gfmo43te0op9-us-east-1/20192756Um-f5-existing-stack-payg-2nic-bigip.template.txt

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/standalone/2nic/existing-stack/payg

Also tried 3-nic too. 

## Severity Level
3

**Comment by JeffGiroux** [comment]
![Screen Shot 2019-10-01 at 1 04 50 PM](https://user-images.githubusercontent.com/22737156/66086919-85577800-e52a-11e9-9a8f-20f73bc887d6.png)

**Comment by JeffGiroux** [comment]
Might be dupe to https://github.com/F5Networks/f5-aws-cloudformation/issues/68

**Comment by alaari-f5** [comment]
this is fixed.
