### ISSUE TITLE
cannot select nonexistent value at index 1

### ISSUE THREAD

**Issue by bertvandevoorde** [F5Networks/f5-aws-cloudformation#80]
## Do you already have an issue opened with F5 support?
No

## Description
Describe the problem you're having or the enhancement you'd like to request.
Attempting to launch the standalone 2nic BYOL stack in Frankfurt (euc1-az2)

I receive the error 
Template error: "Fn::Select cannot select nonexistent value at index 1" in the aws console.

## Template
https://s3.amazonaws.com/f5-cft/f5-existing-stack-byol-2nic-bigip.template

## Severity Level
n/a

**Comment by bertvandevoorde** [comment]
I figured it out. When statically assigning IP addresses in the template (as opposed to DYNAMIC) the external VLAN is required to have a secondary address separated with a comma (obviously). If there is no secondary address defined, one gets this rather bizar error.

**Comment by gwolfis** [comment]
Walking into this same error and imo the template should be intuitive and if we deliver the option to either statically configure an IP host address or leave it dynamic this should not deliver this error, please fix it.

**Comment by shyawnkarim** [comment]
I mislabeled this issue in June and missed this bug. We are now tracking this issue internally with ID ESECLDTPLT-2381.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
