### ISSUE TITLE
f5-existing-stack-across-az-cluster-byol-3nic-bigip.template with no public mgmt IP fails deployment

### ISSUE THREAD

**Issue by rreilly-edr** [F5Networks/f5-aws-cloudformation#85]
## Do you already have an issue opened with F5 support?
Yes, #C3130177

## Description
Stack Deployment fails with 
```
Value (us-east-1c) for parameter availabilityZone is invalid. Network interface 'eni-0e5a66edb90b46353' is in the availability zone us-east-1a (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: d5bd5d6f-cdf3-4027-84f4-f92f2e9d32c6)
```

## Template
[https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/byol](https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/byol)

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
as this is a new deployment its only a 3 but it is preventing me from completing my project.

I have also found another similiar issue
[https://github.com/F5Networks/f5-aws-cloudformation/issues/60](https://github.com/F5Networks/f5-aws-cloudformation/issues/60)

it's confusing as the documentation clearly states that you can use a private subnet for mgmt interfaces but it continues to try an create a ip on the public interface.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue. I will do some investigation and then get back to you.

**Comment by rreilly-edr** [comment]
i figured it out, it was PEBCAK
