### ISSUE TITLE
Request support of IPv6 routes failover during HA Failover

### ISSUE THREAD

**Issue by tewfikm** [F5Networks/f5-aws-cloudformation#86]
Case opened at F5 support : C2867931 with associated RFE 753356.
RFE 753356 needs prioritization

## Description:
The AWS Across AZ iApp doesn't support moving IPv6 routes during failover. 
During failover, IPv6 route fails using the aws_advanced_failover iApp (f5.aws_advanced_ha.v1.4.0rc3.tmpl)
Refer to RFE 753356

## Template
AWS HA templates 
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api

## Severity Level
Customer in production since 2 years with BIG-IP in AWS using HA and IPV6. RFE
Severity : 2

**Comment by alaari-f5** [comment]
The Cloud Failover Extension (CFE) is where most of our development effort is focused on at this time - not the failover iApp: 

- https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/
- https://github.com/f5devcentral/f5-cloud-failover-extension 

We can investigate IPv6 route failover support with CFE. Internal ticket: AUTOSDK-85 added to the backlog.

**Comment by shyawnkarim** [comment]
Closing. IPv6 became supported on this [release](https://github.com/f5devcentral/f5-cloud-failover-extension/releases/tag/v1.0.0).
