### ISSUE TITLE
S3 permission issue with latest CFT

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation#87]
## Do you already have an issue opened with F5 support?
no

## Description
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/payg

and possibly other templates

## Severity Level
3

**Comment by JeffGiroux** [comment]
Also suggest to add a test for post template release to validate S3 permissions across all templates. This will help avoid catching in the field.

**Comment by crosbygw** [comment]
Thanks Jeff. We have updated the readme's to use the correct s3 url. We have added the request to test on release into our internal tasks.
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/autoscale/waf/via-lb/1nic/existing-stack/payg#launching-the-template-using-the-aws-launch-stack-buttons

**Comment by JeffGiroux** [comment]
This is happening again ever since latest templates were released today. AWS is throwing access denied S3 errors.
