### ISSUE TITLE
Template failed- Learning 1 NIC BYOD or PAYG

### ISSUE THREAD

**Issue by lisonlp** [F5Networks/f5-aws-cloudformation#89]
**Description**
When using the 1NIC learning template BYOD or PAYG, the stack failed at the webserver creation step with following error: 

" Failed trying to describe product codes for snapshot '2086935114' (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSnapshot.NotFound; Request ID:  eee62151-6a8d-405a-94ab-083a21458e24)"

**Error description**
According to AWS, the error code is because "The specified snapshot does not exist. Ensure that you specify the AWS Region in which the snapshot is located, if it's not in the default Region."

**Template**
f5-full-stack-byol-1nic-bigip.template
f5-full-stack-payg-1nic-bigip.template

**Comment by mslattery** [comment]
I am also seeing this error with the "payg" template.

**Comment by shyawnkarim** [comment]
Thank you for submitting this issue. I was able to reproduce the error and have created Jira Issue #1751 to get this fixed.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

The V2 full stack templates are not encountering this error.
