### ISSUE TITLE
add details in documentation about required internet access ports and protocols

### ISSUE THREAD

**Issue by tthomas0702** [F5Networks/f5-aws-cloudformation#90]
Documentation improvement

A deploy failed to set up the HA cluster because they had a firewall that did not allow ICMP, and the onborad.js script failed when it could not ping  f5.com (104.219.111.168). 

They were using this template:
/supported/failover/across-net/via-api/2nic/existing-stack/byol

In the "Prerequisites and configuration notes" Section it states:
'''
External subnet (the subnet for the external network requires a route and access to the Internet for onboarding BIG-IP).
'''

It may help avoid this if we state the specific ports and protocols that need to be allowed.  In this case the need to allow  ICMP out.

**Comment by shyawnkarim** [comment]
Thank you for reporting this. This enhancement request to our documentation is now being tracked internally with ID ESECLDTPLT-1972.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

Our documentation for V2 addresses this.
