### ISSUE TITLE
Add chargeback tag - BIG-IQ licensing

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-aws-cloudformation#92]
## Description
Add support for BIG-IQ chargeback tag (BIG-IQ licensing of type "Utility")

## Template
f5-bigiq-autoscale-bigip-waf.template
f5-bigiq-autoscale-bigip-ltm.template

## Severity Level
Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us about this. I've gone ahead and added this RFE to our backlog, internal ID ESECLDTPLT-1664.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

If this feature is still important to you, please submit an issue in the V2 repo.
