### ISSUE TITLE
BIG-IQ Utility licensing, missing sku-keyword-2 to select proper license

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-aws-cloudformation#93]
## Description
The CFT (latest, v5.3.0) doesn't support option **sku-keyword-2** (althought cloudlibs onboard.js does).
My BIG-IQ utility pool has all kind of bandwidth licenses, such as:
F5-BIG-MSP-BT-25M
F5-BIG-MSP-BT-200M
F5-BIG-MSP-BT-1G

Result: BIG-IQ will always pick the license with the lowest bandwidth (first in the list probably, in my case F5-BIG-MSP-BT-25M) and I can't license higher bandwiths.

## Template
f5-bigiq-autoscale-bigip-*.template

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 2

**Comment by shyawnkarim** [comment]
Thank you for reaching out to use with this issue. I've created internal issue ESECLDTPLT-1928 for this enhancement request.

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 5.8.0](https://github.com/F5Networks/f5-aws-cloudformation/releases/tag/v5.8.0).
