### ISSUE TITLE
Clarification on use of regPoolKeys parameter in BIG-IQ Experimental ARM Template

### ISSUE THREAD

**Issue by s-archer** [F5Networks/f5-aws-cloudformation#94]
## Do you already have an issue opened with F5 support?
No.  As this relates to experimental templates which are not supported.

## Description
Clarification requested for use of regPoolKeys parameter in BIG-IQ Experimental ARM Template, specifically when specifying add-on keys.  The suggested format is: 

`name:key,key,key`

It's not clear how add-on keys should be referenced.  For example, should I use something like this:

`poolName: regKey1,addOnKey1,regKey2,addOnKey2,regKey3,addOnKey3`
 
…or…
 
`poolName: regKey1,regKey2,regKey3,addOnKey1,addOnKey2,addOnKey3`

...or are add-on keys not supported?

## Template
https://github.com/F5Networks/f5-aws-cloudformation/tree/master/experimental/bigiq/licenseManagement/standalone/2nic/existing-stack/byol

## Severity Level

Severity: 2

**Comment by crosbygw** [comment]
Big-iq templates do not currently support add on keys as it is a separate api call that will need to be added into [cloud-libs](https://github.com/F5Networks/f5-cloud-libs) which is the underlining library our templates use.

**Comment by s-archer** [comment]
Thanks for the response.  Can I also confirm that regPoolKeys accepts a single 'magic' ELA key?

**Comment by shyawnkarim** [comment]
This enhancement request is now being tracked internally with ID ESECLDTPLT-2056.

**Comment by shyawnkarim** [comment]
Closing. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).

If this feature is still important to you, please submit an issue in the V2 repo.
