### ISSUE TITLE
Delete Stack Failed

### ISSUE THREAD

**Issue by luckymuk** [F5Networks/f5-aws-cloudformation#95]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.
Delete Stack is not working because S3 bucket is not empty. I am getting following error message.
"The bucket you tried to delete is not empty (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: 05044094997D7A1F; S3 Extended Request ID: P9HWMxVEfxYhvxejd4slz+c848+uhwnEW+x39weoqedkA/7/Hlug3tc8xEVCPtG9VuwjPJr0Zbc=)"

## Template
For bugs, enter the template with which you are experiencing issues below.
I am experiencing issue with all the supported failover AWS templates

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.
Severity: 2
Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your issue. Follow these steps to delete your stack:

1. Navigate to S3.
2. Find the bucket your stack is using and click into it to view its contents.
3. Delete all the contents.
4. Delete the stack.

If this doesn't solve your issue, please let me know.

**Comment by shyawnkarim** [comment]
Closing. Steps provided. Please reach back out if you are still having trouble.
