### ISSUE TITLE
better CFT outputs for use with automation tools

### ISSUE THREAD

**Issue by chen23** [F5Networks/f5-aws-cloudformation#98]
## Description
Please add additional keys to CFT outputs.

Currently the cross-AZ template outputs "Bigip1VipPrivateIp" but does not output "Bigip2VipPrivateIp".  This is a mild annoyance because some tools like Terraform will only output "outputs" and you can not access "resources" to get that information easily.  Ideally add "Bigip2VipPrivateIp".  It would also be nice to add the bucket name that gets created to make it easier to fetch the credentials file.

## Template

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for reaching out with this feedback. I've created internal issue ID ESECLDTPLT-1948 for this enhancement.

**Comment by C0missar** [comment]
I was about to raise the same issue.  However, I'm not sure what the purpose of this EIP/VIP combo is, as anyone building a device is likely to deploy more than one VS, so having one "special" set of IPs pre-allocated but with no VS is not really helpful; it just burns an EIP.  I've been manually deleting them every time I build a pair.

**Comment by f5-applebaum** [comment]
Standalone/Failover Templates really shouldn't be deploying services. This comes from them originally being examples of how to stitch / map things together. 
  
ESECLDTPLT-65 - Make Deploying Example Virtual Services a conditional

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-aws-cloudformation-v2).
